### ISSUE TITLE
Top Language Blank Card for private commits

### ISSUE THREAD

**Issue by michele-grifa** [anuraghazra/github-readme-stats#1009]
**Describe the bug**
The Top Language Card is blank and only the title is showed. I deployed my vercel instance because i only have private repos.

**Expected behavior**
A list of language should appear

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://github-readme-stats-gamma-sand.vercel.app/api/top-langs/?username=michele-grifa&layout=compact&cache_seconds=1800)

**Additional context**

**Comment by rickstaa** [comment]
Related to #1640.

@michele-grifa Thanks for your issue! This behaviour is expected since you currently only have forks. We currently do not fetch data from forks for the language card. A feature request for this can be found in #1437.

**Comment by michele-grifa** [comment]
> Related to #1640.
> 
> @michele-grifa Thanks for your issue! This behaviour is expected since you currently only have forks. We currently do not fetch data from forks for the language card. A feature request for this can be found in #1437.

My problem is that i contribute only to private repos, that doesn't show up in the language card.

**Comment by rickstaa** [comment]
@michele-grifa For the stats card you can use the `count_private` flag to count the private contributions. For the other cards it is also possible to include data from private repositories. I have this working on my self-hosted vercel instance and in my dev environment. You can try it out by using the following query in the [graphql explorer](https://docs.github.com/en/graphql/overview/explorer):

query userInfo($login: String!) {
  user(login: $login) {
    # fetch only owner repos & not forks
    repositories(ownerAffiliations: OWNER, isFork: false, first: 100) {
      nodes {
        name
        languages(first: 10, orderBy: {field: SIZE, direction: DESC}) {
          edges {
            size
            node {
              color
              name
            }
          }
        }
      }
    }
  }
}
You can then use the following in the query variables field.

{"login": "michele-grifa"}

However, if you're using the public vercel instance (i.e. https://github-readme-stats.vercel.app/), it can not work for cards other than the stats card since we do not have access to your private repositories. As a result, we can not count the language bytes. I would therefore advise you to set up your vercel instance. A guide on how this is done can be found [here](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).

**Comment by michele-grifa** [comment]
Thanks for your help, now works. I already had my vercel instance but for some reason didn't work. I updated the forked repo and all works.
