### ISSUE TITLE
When i try to increase  the card_width of the card it does not reflect when i commit my readme 

### ISSUE THREAD

**Issue by pdx97** [anuraghazra/github-readme-stats#1060]
**Describe the bug**

**Expected behavior**

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

**Additional context**

When i try to increase  the card_width of the card it does not reflect when i commit my readme 
![card_width](https://user-images.githubusercontent.com/28250686/118359016-0b5cf100-b59f-11eb-8ab8-59e627e83b9d.PNG)
![card_width1](https://user-images.githubusercontent.com/28250686/118359024-144dc280-b59f-11eb-9a1f-aaa580a1f493.PNG)

**Comment by florianbussmann** [comment]
`card_width` is a language card exclusive option as of now

https://github.com/anuraghazra/github-readme-stats/blob/fef8bc3a4a4ddb12a5c779e7cae18438231845a7/readme.md#L193-L198

With the current codebase you could enlarge the language card, however it does not seem to increase the number of columns used when in compact mode. I would have expected 3 or 4 columns instead of 2.

![Bildschirmfoto 2021-05-16 um 10 42 58](https://user-images.githubusercontent.com/3610244/118391219-7e17ac00-b633-11eb-903d-37089ab3f506.png)

**Comment by rickstaa** [comment]
Related to #1170.
