### ISSUE TITLE
theme idea

### ISSUE THREAD

**Issue by Time-dragon** [anuraghazra/github-readme-stats#1152]
**Is your feature request related to a problem? Please describe.**
Nah. I want a rainbow theme.
**Describe the solution you'd like**
Theme with rainbow colors (and darkened version too)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by anuraghazra** [comment]
Hi @Time-dragon 

We are currently only accepting color combinations from any vscode theme or which has good color combination to minimize bloating the themes collection.

Also note that if this theme is exclusively for your personal use then instead of adding it to our theme collection you can use card customization options

Read our contribution guidelines for more info
