### ISSUE TITLE
Top Lang not showing all languages, github stats with wrong total commit count.

### ISSUE THREAD

**Issue by Lucadecastro** [anuraghazra/github-readme-stats#1180]
**Describe the bug**
The total commit count is innacurate, it seems that it stopped counting at some point.
Top Language is not updating.
Wakatime does not return anything

**Expected behavior**
Total commit count should return the right count
Top Lang should show other languages besides javascript only
Wakatime should return something

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![Captura de tela de 2021-07-10 00-16-10](https://user-images.githubusercontent.com/64559709/125150206-7d236800-e114-11eb-8889-083f888b7bda.png)
![Captura de tela de 2021-07-10 00-16-01](https://user-images.githubusercontent.com/64559709/125150209-7f85c200-e114-11eb-8048-01d0a3c9a2f7.png)
![Captura de tela de 2021-07-10 00-16-35](https://user-images.githubusercontent.com/64559709/125150203-77c61d80-e114-11eb-84ec-280e4f1bb73e.png)

I enabled private commits and updated my contributions, I also enabled "Display languages, editors, os, categories publicly" in Wakatime, none of those worked. I looked at the other issues but I could not find a solution.

Can anyone help me please?

**Comment by MdAtifuzzaman01** [comment]
Same issue happening with me!
Top Languages not updating for many days .
Tried updating many ways . Didn't work

**Comment by Lucadecastro** [comment]
My wakatime just updated, it looks like it takes a while, but the rest is still the same.

**Comment by duktig666** [comment]
Top Lang not showing all languages, github stats with wrong total commit count.    I have also the question.

> My wakatime just updated, it looks like it takes a while, but the rest is still the same.

**Comment by cliff-4** [comment]
I had a similar problem. I added the image via URL and it loaded as follows:
![image](https://user-images.githubusercontent.com/65708785/173159183-8cc1d216-8cda-488e-bbe4-f71811f3f1e7.png)
And that was fine until I changed a repository to public that had some C++ code in it. On refreshing and anything, it remained this way, but if I opened the link it's using as src, I got this:
![image](https://user-images.githubusercontent.com/65708785/173159274-1222a792-6004-4353-8b19-739d5ddb832e.png)
Which was actually the correct one. 
It was weird how they're using the same source link but the output is different. I tried removing the entire snippet of code and re-adding it, but the problem still remained.
(The snippet of code I used: `[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=cliff-4&layout=compact&theme=github_dark&hide_title=false&card_width=300)](https://github.com/anuraghazra/github-readme-stats)`)

What fixed this eventually was adding a `&langs_count=10`, but that should not be required since the default is 5 already. Yet it worked, so hopefully this comes in clutch for someone else in the future.

**Comment by rickstaa** [comment]
@Lucadecastro Thanks for creating this issue. I think the problems you are experiencing are because:
- You are comparing the number of **commits** with the **contributions** (see https://github.com/anuraghazra/github-readme-stats/discussions/1679).
- The fact that we use a 4-hour cache and thus results are not immediately updated (see https://github.com/anuraghazra/github-readme-stats#gradient-in-bg_color).
- Problems in the algorithm that fetches the languages (see https://github.com/anuraghazra/github-readme-stats/issues/1852).
- Problems in the algorithm that fetches the commit (see https://github.com/anuraghazra/github-readme-stats/issues/1515.

I will close this issue for now. If you still are experiencing errors, please comment below.
