### ISSUE TITLE
[Question] How does this work?

### ISSUE THREAD

**Issue by mikeymop** [anuraghazra/github-readme-stats#1213]
Looking at the package.json it appears to point to to `index.js` at the root of the project. This does not exist.

Looking through the code it appears the entrypoint is `api/index.js` however the project gives no indication of where the entrypoint is.

When deploying to vercel is an `index.js` created at the root of the project in order for this to work?
I am curious because I would like to run this project locally on my machine and make modifications from a local node environment before deploying to vercel.

**Comment by rjarman** [comment]
If you want to create an installable module with npm package manager then your module's entry point should be the same as the main: index.js _(you can check it by going to the node_modules folder's packages)_, otherwise, the main key does not play any role in these kinds of development except in some cases. If you delete the param, development environment should be run well but it's necessary to use it to create npm packages.

references:
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#main

**Comment by anuraghazra** [comment]
Hi @mikeymop 

> package.json it appears to point to to index.js

It does not matter in our case since github-readme-stats is not a npm module

> Looking through the code it appears the entrypoint is api/index.js however the project gives no indication of where the entrypoint is.

That file is special to vercel and thats how vercel finds serverless functions
You have to use vercel's cli to run github-readme-stats locally. 


I hope your questions are answered, closing this for now.
