### ISSUE TITLE
Adding images as background

### ISSUE THREAD

**Issue by yashrajb** [anuraghazra/github-readme-stats#1279]
**Is your feature request related to a problem? Please describe.**
Right now we can change only themes but what if someone want images as background

**Describe the solution you'd like**
give options to user to add image as background. all query parameters are listed below with data type.
- bg_img = url
- bg_img_width = number
- bg_img_height = number
- bg_img_blurness = number - to make background blurry

we will only take image url and will also give some parameters for changing width,height and also we will give blurry effect if user wants. i added blur effect because sometimes images have high contrast colors so, it will be hard to see the text.

**Additional context**
So, i already created my own instance in that instance i made those changes. take a look here. play with this examples
- [black background with particles](https://github-stats-pied-omega.vercel.app/api?username=yashrajb&bg_img=https://i.makeagif.com/media/3-27-2018/UdTztL.gif&bg_img_height=280&bg_img_width=500&theme=midnight-purple&bg_img_blurness=0)
- [black background with heat particles](https://github-stats-pied-omega.vercel.app/api?username=yashrajb&bg_img=https://i.pinimg.com/originals/fa/64/f5/fa64f5f6f11b5385548805b9ef3eea1b.gif&bg_img_height=280&bg_img_width=500&theme=midnight-purple&bg_img_blurness=0)
- [urban life](https://github-stats-pied-omega.vercel.app/api?username=yashrajb&bg_img=https://giffiles.alphacoders.com/209/209343.gif&bg_img_blurness=0&bg_img_width=491&bg_img_height=250&bg_img_blurness=3&theme=great-gatsby)
- [code](https://github-stats-pied-omega.vercel.app/api?username=yashrajb&bg_img=https://raw.githubusercontent.com/laudep/code-gif-generator/master/docs/img/generating.gif&bg_img_width=443&bg_img_height=250&theme=chartreuse-dark)
- [clouds](https://github-stats-pied-omega.vercel.app/api?username=yashrajb&bg_img=https://i.pinimg.com/originals/aa/96/97/aa9697a3f7a61389675b8dc109518753.gif&bg_img_width=443&bg_img_height=330&theme=chartreuse-dark)
- [late night](https://github-stats-pied-omega.vercel.app/api?username=yashrajb&bg_img=https://i.pinimg.com/originals/e5/ce/bf/e5cebf7269f86a7b1d1799f0cb1bfa46.gif&bg_img_width=445&bg_img_height=360&bg_img_blurness=1&theme=merko)

Let me know if you are interested guys i already made those changes all i have to do is make PR. Happy to hear your feedback

**Comment by salmanansari14** [comment]
I want to contribute

**Comment by yashrajb** [comment]
> I want to contribute

Hi, salman i already did those changes. if want to contribute you can write test cases. snapshot testing will not work due to changes in /src/Card.js

**Comment by anuraghazra** [comment]
This is cool @yashrajb!

But unfortunately it wont work in github markdown, since these are served as svg images it will not get a chance to load the image URL. 

![](https://github-stats-pied-omega.vercel.app/api?username=yashrajb&bg_img=https://i.makeagif.com/media/3-27-2018/UdTztL.gif&bg_img_height=280&bg_img_width=500&theme=midnight-purple&bg_img_blurness=0)

![](https://github-stats-pied-omega.vercel.app/api?username=yashrajb&bg_img=https://raw.githubusercontent.com/laudep/code-gif-generator/master/docs/img/generating.gif&bg_img_width=443&bg_img_height=250&theme=chartreuse-dark)

![](https://github-stats-pied-omega.vercel.app/api?username=yashrajb&bg_img=https://i.pinimg.com/originals/fa/64/f5/fa64f5f6f11b5385548805b9ef3eea1b.gif&bg_img_height=280&bg_img_width=500&theme=midnight-purple&bg_img_blurness=0)

**Comment by yashrajb** [comment]
i created pull request if you think there is something you can do then check it out. because i am deleting instance now from vercel https://github.com/anuraghazra/github-readme-stats/pull/1283

**Comment by anuraghazra** [comment]
yeah sorry but this won't actually work.

**Comment by anuraghazra** [comment]
closing it via #1283.
