### ISSUE TITLE
Missing space in Total stars received

### ISSUE THREAD

**Issue by MedzikUser** [anuraghazra/github-readme-stats#1290]
**Describe the bug**
Space is missing in Total stars received in this url: https://github-readme-stats.vercel.app/api?username=MedzikUser&show_icons=true&theme=radical&line_height=27&include_all_commits=true&count_private=true

![bb](https://github-readme-stats.vercel.app/api?username=MedzikUser&show_icons=true&theme=radical&line_height=27&include_all_commits=true&count_private=true)

**Expected behavior**
I would expect something like this: https://github-readme-stats.vercel.app/api?username=anuraghazra

![aa](https://github-readme-stats.vercel.app/api?username=anuraghazra)

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![ss](https://cdn.magicuser.cf/dTxbz97.png)

**Comment by ManishBB** [comment]
Is this issue still open, I want to fix it

**Comment by anuraghazra** [comment]
The "received" wording accidentally merged and deployed without proper testing in #1207

We are yet to decide on which wording to use - "gained", "received", "earned" or "obtained"

Currently i've reverted the change so this issue is obsolete. closing it for now, will change the wording and fix the spacing along with tat
