### ISSUE TITLE
[Feature Request] Pin gists the way we pin repos

### ISSUE THREAD

**Issue by forkbabu** [anuraghazra/github-readme-stats#13]

**Comment by anuraghazra** [comment]
Thanks @forkbabu i'll see what i can do :D

**Comment by nombrekeff** [comment]
That would be a cool addition :)

**Comment by anuraghazra** [comment]
@nombrekeff yup, although i don't know how do i handle the syntax highlighting because github-readme-stat returns SVG images and it has to be static. so i think i might have to write a whole syntax highlighter for svg elements.. 

also SVG texts are not really optimal in terms of alignment, it's a real pain to get things where we want.

**Comment by nombrekeff** [comment]
Ohh, I see, definitely tricky... Didn't think about that... maybe just show the title and description and star count?

Even if you could highlight the code, you wouldn't want to show the full gist. I would imagine as it would take a lot of space.

**Comment by anuraghazra** [comment]
yes true... maybe i can just show the gists stats

**Comment by nombrekeff** [comment]
I haven't looked at the source code yet, but I will be taking a look at it this evening and will try and help you out a bit with this.

**Comment by anuraghazra** [comment]
Sound good to me :D

**Comment by dms24081999** [comment]
> 
> 
> Ohh, I see, definitely tricky... Didn't think about that... maybe just show the title and description and star count?
> 
> Even if you could highlight the code, you wouldn't want to show the full gist. I would imagine as it would take a lot of space.

Github Gist's doesn't have a title, it only has a Description(optional field), and Files(1 or multiple files) in same gist and gist URL (uniquely generated ID) and star can be counted.

---
### Opt-1:
The project has to use unique ID (randomly generated by Github for Gists) instead of title, since description is optional.

### Opt-2:
Let user enter the Gist title in the URL of the API ```/api?gist_title=Sample-for-Hello-world&...```.

### Opt-3:
Let the user decide to use Unique ID of Gist as title OR enter title in the URL of the API.

**Comment by nthnchu** [comment]
> yup, although i don't know how do i handle the syntax highlighting because github-readme-stat returns SVG images and it has to be static. so i think i might have to write a whole syntax highlighter for svg elements..
>
> also SVG texts are not really optimal in terms of alignment, it's a real pain to get things where we want.

The only solution I have is to use `<foriegnObject>` and [Prism](http://prismjs.com) (which can be used backend I think). IMO the pinned gist card should look like a github pinned gist, so it should have a preview of the code...

**Comment by anuraghazra** [comment]
I've decided that we won't include this feature even if it's possible since github-readme-stats is focused toward showing statistics and not the gist's contents, so it would be rather nice if we could do something like "Github Gist Stats" Which would show stats of total gists and stars on the gists but this gists card we won't include at the moment. 

Feel free to open another issue for further discussions.
