### ISSUE TITLE
Automatic bad issue closer

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#1493]
**Is your feature request related to a problem? Please describe.**

I would like to prevent people from filling in the BUG or Issue templates. Issues like #1426 where only the title is used are confusing and clutter the issue backlog.

**Describe the solution you'd like**

Maybe it is an idea to use the https://github.com/lucasbento/auto-close-issues action to automatically close issues that do not contain the bug or feature template or that do not modify these templates. @anuraghazra if you like this idea I can modify https://github.com/lucasbento/auto-close-issues to also close templates that are not modified.

**Comment by anuraghazra** [comment]
Hi @rickstaa yup I've seen few issues with just title and even those title are useless, but I'm not sure if this a good idea. 
Don't think we need to force this because even if we do it will just encourage the issuer to copy paste the title of the issue in the body + the volume of low effort issues aren't that high we can manage it manually. 

Plus a simple well written title can make the issue obvious.
