### ISSUE TITLE
Feature: Include pull request data in Most Used Languages card

### ISSUE THREAD

**Issue by joeljosedev** [anuraghazra/github-readme-stats#1534]
The current **Most Used Languages** card only shows data from repositories the user has created. But I think the data from pull requests that the user has submitted should also be included in this card. So, I think it would be a good feature to have and would really show the top languages of the user.

**Comment by lsalvadore** [comment]
I support this suggestion, and I also add that pull requests is not the only way to contribute to others' repositories. There are also repositories owned from organizations and teams you are in and for which you have write access.

More generally, I think any commit associated with your account should contribute to your langauges statistics.

**Comment by rickstaa** [comment]
@joeljosedev and @lsalvadore, thanks for your feature request. I am, however, afraid that what your asking for is not possible with the current GitHub GraphQL API. See https://github.com/anuraghazra/github-readme-stats/issues/1801#issuecomment-1176153879 for more information. I created a feature request to improve the GraphQL API so that we can improve the language results. Please give your support for this feature at https://github.com/orgs/community/discussions/18230. I will close this request for now. Feel free to ping me if the GraphQL API adds https://github.com/orgs/community/discussions/18230.
