### ISSUE TITLE
suport commit chart.

### ISSUE THREAD

**Issue by kingreatwill** [anuraghazra/github-readme-stats#154]
https://github.com/Bloggify/github-calendar

https://github.com/Sobranier/github-chart

**Comment by terror** [comment]
Not entirely sure why we'd support the commit chart if the commit chart is already present on the GitHub profile?

**Comment by anuraghazra** [comment]
Hey thanks for requesting the feature @kingreatwill, Yes true, github-readme-stats focused with the stats that are not visible on the GitHub UI. And also this feature is out of the scope of this project.

**Comment by nombrekeff** [comment]
Yeah, I don't think this would fit into the current scope. Also, there are projects that do this already.

**Comment by anuraghazra** [comment]
Hi @kingreatwill thanks for requesting the feature, we decided to not implement this since contribution chart is already there and people can see, plus we don't wanna bloat the service with lots of features which are already there on the github's UI.

Thanks for the request tho, feel free to open another issue if you have any other ideas. :smile:
