### ISSUE TITLE
GitHub Stats "circle" is a bit confusing if you don't understand how the "ring completion" is put together.

### ISSUE THREAD

**Issue by stemount** [anuraghazra/github-readme-stats#160]
**Is your feature request related to a problem? Please describe.**
Imagine yourself as a hiring manager and you know a little bit about GitHub, but not a lot about this new README.me craze.
I actually haven't fully studied the code to see why this works, but I have done this on purpose to put myself in the shoes of the above.

It is really confusing as to why `A++` looks like 60% out of 100% on the round circle.

A++ is very confusing here. Why does it look like you've got a super duper score but the "ring" looks no way near complete?

**Describe the solution you'd like**

Two things:

1. [Big change] We could find a new way to represent the A++. I think the "ring" should be more like a fitness band ring which would add a load more new lovely colours to the widget. The rings would essentially be a "ratio" of issues : pull requests : commits etc…
2. A++, A+, etc become 100%, 80% respectively on the ring?

**Additional context**

This is an example of A++ I refer to...
<img width="508" alt="image" src="https://user-images.githubusercontent.com/150512/88291828-bb9bf900-ccf0-11ea-974e-b94590bea7fe.png">

**Comment by anuraghazra** [comment]
Hi @stemount thanks for pointing this out.

actually we have   B+, A+, A++, S,  S+ ranks

And the ranks are distributed intentionally in a curved manner so that more people get A+ & A++ and S, S++ Ranks are super hard to get. 

Also note that these are just activity stats, and ranks represents the user's activity on github not how skilled a user is *(Same as github's contribution chart)*, so if a hiring manager is judging a user by these ranks they should add a note about the ranks or point them about the rank's actual use.

> The rings would essentially be a "ratio" of issues : pull requests : commits etc…
Yes they are calculated depending on these stats.

**Comment by EvgenyOrekhov** [comment]
> actually we have B+, A+, A++, S, S+ ranks

What do those letters and pluses mean? This is really confusing.

**Comment by stemount** [comment]
Yeah I also share confusion on S++ as A++/A+/B+ seem like very good grades to me and without knowing what S and S+ mean the ring just looks broken.
