### ISSUE TITLE
Add total lines of code changed 

### ISSUE THREAD

**Issue by JakeWasChosen** [anuraghazra/github-readme-stats#1606]
**Describe the solution you'd like**
Add total lines of code changed in the github stats card 
(see additional context for example)

You could get this info by looping through all repo's and
using the https://api.github.com/repos/{{repo}}/stats/contributors 
endpoint

**Additional context**
<img src="https://i.imgur.com/eDDI0Gk.png"></img>

**Comment by rickstaa** [comment]
@JakeWasChosen Thanks for your feature request. I have to say that I'm not a big fan of including the lines of code into the stats card. This is because the number of lines of code is, in my opinion, not a good measure of a programmer's experience and code quality. 

I will however leave this pull open to get feedback from the rest of the community.

**Comment by anuraghazra** [comment]
Hi @JakeWasChosen thanks for the request, I agree with rick plus to add more to the statement it's gonna be very expensive to compute the number of lines for each and every repository, So i don't think it's very viable for us to implement this.
