### ISSUE TITLE
no of prs against my account is not correct at all. Total pr in my account is around of 100 but it is sowing that it is only 7.

### ISSUE THREAD

**Issue by keder-code-hash** [anuraghazra/github-readme-stats#1622]

**Comment by anuraghazra** [comment]
We need more info do debug this. 

Note that: 
- We don't count private pull requests. 
- This stat is only for this year.

**Comment by keder-code-hash** [comment]
Yeah,I got the reason for my issue . It was private pull request.

**Comment by usman10scorpio** [comment]
You do not count private pull request but you count private commits why ?

**Comment by rickstaa** [comment]
@usman10scorpio Thanks for your question. This is because people can choose to share the private commit count on their profile (see picture). The private PR count can not be shared publicly. For other private stats to show up, you should deploy your won Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).

![image](https://user-images.githubusercontent.com/17570430/204649949-da5649c5-f166-49d0-a81c-a3a0f75bcb86.png)
