### ISSUE TITLE
vercel  build errpr

### ISSUE THREAD

**Issue by gujiwuqing** [anuraghazra/github-readme-stats#1638]
**Describe the bug**
## The value for maxDuration must be between 1 second and 10 seconds, in order to increase this limit upgrade your plan: https://vercel.com/pricing

**Expected behavior**

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

**Additional context**

**Comment by rickstaa** [comment]
@gujiwuqing Thanks a lot for your issue. This is as expected since we need the max duration to be higher for the public vercel instance. This can be solved by lowering the `maxDuration`  in the `vercel.json` file (see https://github.com/anuraghazra/github-readme-stats/commit/8af4544dad025dfd770b99bf48278728217a8f0d, https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance and https://github.com/anuraghazra/github-readme-stats/issues/1416).

**Comment by gujiwuqing** [comment]
> @gujiwuqing Thanks a lot for your issue. This is as expected since we need the max duration to be higher for the public vercel instance. This can be solved by lowering the `maxDuration` in the `vercel.json` file (see [8af4544](https://github.com/anuraghazra/github-readme-stats/commit/8af4544dad025dfd770b99bf48278728217a8f0d), https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance and #1416).

thank you so much i'll check it out
