### ISSUE TITLE
Some languages aren't showing in most used section

### ISSUE THREAD

**Issue by TimAppleCodes** [anuraghazra/github-readme-stats#1678]
**Describe the bug**
I have css, python, dart, and some c++ in my github, but only the python and CSS show up. 

**Expected behavior**
I would like to see the Dart show up

**Additional context**

**Comment by rickstaa** [comment]
@TimAppleCodes Thanks for your issue. I double-checked your profile using https://docs.github.com/en/graphql/overview/explorer and I think the card is working fine. You can check this out using the following query:

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    # fetch only owner repos & not forks
    repositories(ownerAffiliations: OWNER, isFork: false, first: 100) {
      nodes {
        name
        languages(first: 10, orderBy: {field: SIZE, direction: DESC}) {
          edges {
            size
            node {
              color
              name
            }
          }
        }
      }
    }
  }
}
```

```graphql
{"login": "TimAppleCodes"}
```

I, therefore, think your issue is related to https://github.com/anuraghazra/github-readme-stats/issues/1640 and https://github.com/anuraghazra/github-readme-stats/issues/1009. As explained in https://github.com/anuraghazra/github-readme-stats/issues/1009#issuecomment-1068833200 you should deploy your own vercel instance if you want languages of private repositories to show up. A guide on how this is done can be found [here](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).

Hope that helps. Let me know if you have any other questions.

**Comment by redital** [comment]
I have the same problem here, MATLAB and Tex are not showed, I tought it was because the repo is private, so I switched to public just to check but nothing changed. So I setted the repo to private again.
It's not a big deal but it wuold be great if there was an option to include privates repos as for the total commits in the stats card.

**Comment by rickstaa** [comment]
@redital It should work without any problems. I think the reason you were not seeing your commits was that we use a cache period of a maximum of 4 hours to decrease the API load (see https://github.com/anuraghazra/github-readme-stats#customization). The best solution however is to deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance).
