### ISSUE TITLE
Make the commits accurate

### ISSUE THREAD

**Issue by Kiyoshi-23** [anuraghazra/github-readme-stats#1681]
**Is your feature request related to a problem? Please describe.**
The total commits shown shows the commits for deleted repos as well. 
**Describe the solution you'd like**
Should only show commits for repos that are not deleted and still open. 
**Describe alternatives you've considered**
Make it where it only shows commits for repos that are still not deleted and open. 
**Additional context**
![Screen Shot 2022-03-22 at 8 37 57 PM](https://user-images.githubusercontent.com/90008981/159604714-025d3184-1c4f-49af-9e85-3b3376e1da79.png)
![Screen Shot 2022-03-22 at 8 38 14 PM](https://user-images.githubusercontent.com/90008981/159604733-f90eed2c-59c4-464f-91be-ed0b4c224562.png)

**Comment by rickstaa** [comment]
@Kiyoshi-23 Thanks for your feature request. If commits of deleted repositories are counted this seems like an upstream issue. We use the [GraphQL API](https://docs.github.com/en/graphql/reference/object) for retrieving our data. (i.e. [contributionscollection ](https://docs.github.com/en/graphql/reference/objects#contributionscollection) field). As a result, if these queries include deleted commits they will show up on the stats card. Since GraphQL to my knowledge doesn't have a way to filter out deleted commits it is infeasible to implement your feature at the current time. You can check the fetching behaviour in the [GraphQL explorer](https://docs.github.com/en/graphql/overview/explorer) using:

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    repositories(first: 100) {
      totalCount
      nodes {
        name
      }
    }
    contributionsCollection {
      totalCommitContributions
      restrictedContributionsCount
      commitContributionsByRepository(maxRepositories: 25) {
        repository {
          name
        }
        contributions {
          totalCount
        }
      }
    }
  }
}
```

```graphql
{
  "login": "Kiyoshi-23"
}
```
