### ISSUE TITLE
Total lines of code for user

### ISSUE THREAD

**Issue by cherryleafroad** [anuraghazra/github-readme-stats#1692]
Not sure if this is actually possible with the GitHub system, but if possible, it would be wonderful if `Total Lines of Code Written` could be included in the card.

I figure a reason it might not be yet is because it's not possible, but doesn't hurt to check since I don't see anything about it

Edit: Just found #1606 , I suppose this will not be changed then. (Although I agree it should be optional). I'll leave this open I guess, but I expect it'll probably be closed fairly quickly

**Comment by rickstaa** [comment]
@cherryleafroad Thanks for creating this issue. You're right; we briefly discussed this in #1606. However, let me clarify some things about that issue. I myself don't have something against giving users the ability to show the lines of codes they wrote. It might be fun to see how many lines somebody wrote during their developer career. I, however, don't think it should be included in the rank calculation since it is not a good measure of developer proficiency or community contribution. However, if there is an inexpensive way to get the lines of code, I'm fine with providing that option.

**Comment by cherryleafroad** [comment]
Yes. I agree it's certainly not a metric of how good somebody is, although it's definitely an interesting stat.

And I also agree that if it's expensive, it's not feasible to do.

My guess is that the current way would probably be to have to go through every single repo, which would exponentially increase the time taken, right?

**Comment by avgupta456** [comment]
Consider using github.com/avgupta456/github-trends. I built this project specifically to track lines of code written by language and repository. Let me know what you think!

**Comment by rickstaa** [comment]
@avgupta456 Thanks for jumping in on this treat and bringing [github.com/avgupta456/github-trends](https://github.com/avgupta456/github-trends) to my attention! 

@avgupta456 is @cherryleafroad card what you had in mind, or did you want to show the total number of coded lines on the stats card?

If the latter is the case, I think I have to disappoint you. As far as I can see, the GraphQL API does not contain a `totalAdditions` or `totalDeletions` object on the user or repository level. As a result, the lowest big O complexity that can be achieved equals the number of commits `N` made by a user. I, however, could not find the correct syntax for this without first fetching the `userId` or `commitId`. Further, this data is limited by Github's [node limits](https://docs.github.com/en/graphql/overview/resource-limitations). I, therefore, think keeping this information on a separate card like the one by @avgupta456 is currently the best option since adding this logic here might cause us to reach the Github timeouts or lead to a very slow card load times.

For example, the following query, for a user with relatively low commits, works fine:

```graphQl
query userInfo($login: String! $userId: ID!) {
  user(login: $login) {
    id
    repositories(ownerAffiliations: OWNER, isFork: false, first: 100) {
      nodes {
        name
        defaultBranchRef {
          target {
            ... on Commit {
              additions
              deletions
              history(author: {id: $userId}) {
                nodes {
                  additions
                  deletions
                }
              }
            }
          }
        }
      }
    }
  }
}
```

```graphql
{
  "login": "sc0", "userId": "MDQ6VXNlcjIxODAxNzQ"
}
```

But when I try with my user account, I run into a timeout.

```graphql
{
  "login": "rickstaa", "userId": "MDQ6VXNlcjE3NTcwNDMw"
}
```

Feel free to let me know if you found a syntax that is less computationally intensive. We could reconsider adding this information to the stats card if the GraphQL API changes so that we can retrieve the total additions/deletions for a user or repository directly without going through the separate commits/files. For now, however, I think we can close this issue.

**Comment by rickstaa** [comment]
Reaching this limits can be seen when I use my user account with the githubtrends 
[![GitHub Trends SVG](https://api.githubtrends.io/user/svg/rickstaa/repos?time_range=one_year&theme=classic)](https://githubtrends.io)
