### ISSUE TITLE
[Feature] Detect private repositories in Top Languages card

### ISSUE THREAD

**Issue by Nathan13888** [anuraghazra/github-readme-stats#174]
**Is your feature request related to a problem? Please describe.**
Top Languages Cards do not display anything about private repositories **even when using a self-deployed Vercel instance**.

Since the majority of my repositories are private and any public repositories are either forks or don't have any particular "Language" being used, the Top Languages Card appears to be blank (view my profile for details).

**Describe the solution you'd like**
Include private repositories when generating the Top Languages card.

**Describe alternatives you've considered**
No other than not using this feature.

@FabioRosado Do you have any ideas?

**Comment by anuraghazra** [comment]
Hmm i see, so you have 3 public repos 2 of them are forked and 1 is a profile readme thats why languages are not shown. 

So in case of private repos,
I don't think we can access any private repos, so we cannot calculate languages from private repos.
Also note that i'm not too good at security or privacy terms of github, that's why i'm avoiding showing any private info which is not directly given to an unauthenticated user through github's API, I accepted the implementation of count_private because github api allows it directly with user's consent. 

Yes you can deploy on your own vercel instance and fork/modify the code to show your private repo languages.

**Comment by FabioRosado** [comment]
Hello @Nathan13888  What you are asking will not be possible with @anuraghazra  hosted version, this is because the graphql query will check  the [Repository object](https://docs.github.com/en/graphql/reference/objects#repository) and will count the languages if a repository is not a fork ([Line 11 of fetchTopLanguage](https://github.com/anuraghazra/github-readme-stats/blob/f9b14c9442276fd30119183e0b5f0695e9420d09/src/fetchTopLanguages.js#L11)).

The only way for you to get the languages on your private repos count towards your stats would be to host the project yourself - this is because when you use your own API key you will have access to all your private data anyway. 

Also note that the languages counter will check if a repository is not a fork so it will only count repos that were created by you and not a fork from another project.  We could count all the repos instead but that will just make @anuraghazra  hit the api limits quicker I believe.

I guess as a work around you could fork this repo, change the query on fetchTopLanguages to turn the [Line 11 of fetchTopLanguage](https://github.com/anuraghazra/github-readme-stats/blob/f9b14c9442276fd30119183e0b5f0695e9420d09/src/fetchTopLanguages.js#L11) to true and should start count the languages of your forked projects.

Hope this helps 😄 👍

**Comment by anuraghazra** [comment]
@FabioRosado 
> We could count all the repos instead but that will just make @anuraghazra hit the api limits quicker I believe.

Actually we have multiple Personal Access Token Fallbacks (see #58) so it's unlikely that we will hit the rate limit, the main issue is performance, fetching all the repos will take time and since github api paginates the response to 100 repos we actually have to do multiple requests to get all the repos and that would take some time and it runs on free tier of vercel so the serverless function will fail after 10 seconds, i know 10 seconds sounds too much but surprisingly enough it's not, this is the reason why the #15 is pending.

> will count the languages if a repository is not a fork (Line 11 of fetchTopLanguage). 

Yes we skip over forks, because forks are not the right metric imo, because a user can fork as many as big repos they want and if we count that in the stats will be too biased.

**Comment by FabioRosado** [comment]
Didn't know about that but that's a great way to do things! Also I do agree that we should skip forks, this was mostly to try and help @Nathan13888 question/request haha

**Comment by anuraghazra** [comment]
@FabioRosado Yup! :+1: 

@Nathan13888 I think the best approach is to fork and modify the code on your end, let me know if that solves your query and we can close this for now.

**Comment by MirayXS** [comment]
> The only way for you to get the languages on your private repos count towards your stats would be to host the project yourself - this is because when you use your own API key you will have access to all your private data anyway.
@FabioRosado 

My hosted project

<img src="https://github-readme-stats-mirayxs.vercel.app/api/top-langs/?username=MirayXS">

This project

<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=MirayXS">

Shows the same value. So it doesn't count private repos.

**Comment by MirayXS** [comment]
If it counted private repos, i would've had a high javascript % as i work on javascript private projects

**Comment by Nathan13888** [comment]
I've actually tried hosting my own vercel instance already but it doesn't work still. @anuraghazra

So the solution from the previous feature request that @FabioRosado suggested doesn't seem to work here.

Could there potentially have been some sort of secret API or setup that allows for this to work?

**Comment by Nathan13888** [comment]
I've added a self-deployed/hosted version of the repository for reference on my profile picture.

**Comment by anuraghazra** [comment]
@Nathan13888 @MirayXS as I said, you have to *modify the code* so that it also counts private repos, it does not just magically work just by using your own PAT. 

> Yes you can deploy on your own vercel instance and **fork/modify the code** to show your private repo languages.

**Comment by MirayXS** [comment]
I already have a fork and hosted instance. What code and lines I have to modify ?

**Comment by anuraghazra** [comment]
@MirayXS setting isFork: false should work

https://github.com/anuraghazra/github-readme-stats/blob/f50938c908014e3cb657ee34bead91f64e9eb498/src/fetchTopLanguages.js#L11

**Comment by anuraghazra** [comment]
@MirayXS setting isFork: true should work

https://github.com/anuraghazra/github-readme-stats/blob/f50938c908014e3cb657ee34bead91f64e9eb498/src/fetchTopLanguages.js#L11

**Comment by xiaoyu2006** [comment]
> I already have a fork and hosted instance. What code and lines I have to modify ?

If everything is as that easy...

**Comment by anuraghazra** [comment]
> > I already have a fork and hosted instance. What code and lines I have to modify ?
> 
> @anuraghazra If everything is as that easy... It'll be a huge project to clone those repos and count.

https://github.com/anuraghazra/github-readme-stats/issues/174#issuecomment-663590879
https://github.com/anuraghazra/github-readme-stats/issues/174#issuecomment-663638201

**Comment by xiaoyu2006** [comment]
> It's not about huge projects or cloning repo in order to fetch calculate the data. all is done from `Github GraphQL API`

I haven't done anything like this before. 😨

**Comment by anuraghazra** [comment]
> > It's not about huge projects or cloning repo in order to fetch calculate the data. all is done from `Github GraphQL API`
> 
> I haven't done anything like this before.

Everything is magic then :wink: 

You can explore the API here: 
- https://developer.github.com/v4/explorer/

Also check out the code please: 

https://github.com/anuraghazra/github-readme-stats/blob/f50938c908014e3cb657ee34bead91f64e9eb498/src/fetchTopLanguages.js#L5-L27

**Comment by MirayXS** [comment]
>            repositories(isFork: false, first: 100) {

i want to only count private

**Comment by odieone44** [comment]
> You can explore the API here:
>
>    https://developer.github.com/v4/explorer/

trying 
```
viewer {    
    repositories(isFork: false, first: 100) {
      nodes {
        name
     }
   }
}
```

on api explorer shows private repos fine without needing the isFork value to be true. 

When trying the languages query in the API Explorer I did have to change the language(first:1) to (first:10) to get details on more languages, havent looked at the rest of the source code to see if it would make any difference in this issue though. 

In any case the language tracker does not seem to work the same way.

As a sidenote i have this weird difference while deploying on my own (1st pic is from your api, second from mine)

![image](https://user-images.githubusercontent.com/39122638/88457447-25520980-ce8f-11ea-868a-718fbc808a2f.png)

**Comment by anuraghazra** [comment]
@odieone44 
> As a sidenote i have this weird difference while deploying on my own (1st pic is from your api, second from mine)

Probably because your instance is using your own PAT so it's also fetching all the private contributions and stats.

**Comment by xiaoyu2006** [comment]
> @anuraghazra If everything is as that easy... It'll be a huge project to clone those repos and count.

@anuraghazra OMG. I was meant to post these things under #168 ... Found this just now...

**Comment by MirayXS** [comment]
> > ```
> >        repositories(isFork: false, first: 100) {
> > ```
> 
> i want to only count private repositories, this only counts forked repositories

**Comment by RegsonDR** [comment]
After you host an instance (with the latest code), you need to create an access token which has the "repo" scope. This will include your private repositories in the calculation.  You don't need to change any code. @MirayXS

**Comment by martin-mfg** [comment]
Hi, I'm maintaining a fork of github-readme-stats [here](https://github.com/stats-organization/github-stats-extended). On top of the existing functionality I added [support for private contributions](https://github.com/stats-organization/github-stats-extended/blob/master/docs/fork.md#private-contributions-support) and other enhancements while remaining compatible with github-readme-stats.

So if you are looking for an easy way to include private contributions in your languages card without setting up your own instance of github-readme-stats, this may be helpful.
