### ISSUE TITLE
im getting a token error while using vercel

### ISSUE THREAD

**Issue by prathikshetty2002** [anuraghazra/github-readme-stats#1754]
I was using the github readme stats from quite a while. Now this error pops up that i need to include an env variable called PAT_1 in my github token at vercel. what does it means? i have tried to lookup but can't find a satisfactory solution.

here it is : 

![Screenshot 2022-05-18 002114](https://user-images.githubusercontent.com/63772910/168888557-833ad51f-f111-475b-9565-cc5e5a0b0583.png)

my readme file : 

![Screenshot 2022-05-18 002151](https://user-images.githubusercontent.com/63772910/168888620-24cf35af-7f72-471d-9bad-cb631789c3bd.png)

how can i get back to the normal state. also will the progress card will be lost?

**Comment by Geoffery10** [comment]
I had it too but seems fixed now. Likely a server problem.

**Comment by Ryah** [comment]
I'm having that issue now currently. Glad to see it's not something I did wrong.

**Comment by pallavgupta** [comment]
+1

**Comment by nibitoff** [comment]
+1

**Comment by nibitoff** [comment]
same problem

**Comment by ppizarror** [comment]
Issue solved. Just press Shift+F5 on your browsers to remove the image cache. And then you should be able to see your beautiful stats >)

**Comment by Pi-31415** [comment]
Same problem here. Seemingly it's a server problem... Shift+F5 does not work.

**Comment by nathan-pham** [comment]
Yeah a full refresh doesn't seem to work

**Comment by MA-Ahmad** [comment]
I'm facing same issue.

**Comment by bpires** [comment]
Same issue here, started earlier.. did go away briefly, and now is happening again. Full refresh won't do!... Wish I knew how to help!

**Comment by Bdbmzwsc** [comment]
+1

**Comment by aimclee** [comment]
me neither. Shift +F5 is not working...

**Comment by the-eduardo** [comment]
+1
looks like a problem with [readme-stats](https://github.com/anuraghazra/github-readme-stats)

**Comment by nonlinearthink** [comment]
+1

**Comment by the-eduardo** [comment]
https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s

Here is how to fix [#58](https://github.com/anuraghazra/github-readme-stats/pull/58)

**Comment by xiaozuo7** [comment]
Everyone encounters this problem, it can prove that I have no problem.🍮

**Comment by rk0cc** [comment]
> me neither. Shift +F5 is not working...

Me too :(

**Comment by growthbeing** [comment]
Facing same issue.

**Comment by rk0cc** [comment]
Now worked out of nowhere...

**Comment by growthbeing** [comment]
> worked out of nowhere (for me)...

It's working for me as well just now. The issue might have been resolved.

**Comment by anuraghazra** [comment]
You can [deploy on your own vercel ](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)instance in the meanwhile to fix the issue.

For more info see https://github.com/anuraghazra/github-readme-stats/issues/1471

**Comment by growthbeing** [comment]
> You can [deploy on your own vercel ](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance)instance in the meanwhile to fix the issue.
> 
> For more info see #1471

Thanks.

**Comment by rickstaa** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Got bombarded with github notifications today. 🥲<br>Because github-readme-stats is down.<br><br>People don&#39;t understand that &quot;+1&quot; and &quot;same here&quot; comments don&#39;t help anyone, it&#39;s just puts pressure on the maintainer and spams their inbox.</p>&mdash; Anurag Hazra ⚛ (@anuraghazru) <a href="https://twitter.com/anuraghazru/status/1526842284167245824?ref_src=twsrc%5Etfw">May 18, 2022</a></blockquote>

@yhancarloSPM This problem is affecting all users of the public Vercel instance. For people who experience this problem, please wait until we fix this issue upstream or as mentioned in https://github.com/anuraghazra/github-readme-stats/issues/1471 deploy your own vercel instance. Locking this issue, for now, to keep the notification bar from exploding 🤯.
