### ISSUE TITLE
Why contributions to forks aren't considered in calculations?

### ISSUE THREAD

**Issue by mouashmawy** [anuraghazra/github-readme-stats#1812]
The Most used language card isn't considering contributions to other's repositories through being contributor their or by forking.

Please consider adding it

**Comment by rickstaa** [comment]
@mouashmawy Thanks for your feature request! I will answer both options, including forks and stats from repositories to which users contributed separately.

A PR was recently created to include the results of the fork (see #1803). It was, however, closed due to the current GraphQL implementation. Currently, the GraphQL API does not allow us to fetch language results for individual users. It only returns language results for repositories. As a result, the language card is already not showing the correct statistics. Adding support for forks would make this problem worse. The GraphQL API has to be extended to allow forks to be supported. I created a feature request with GitHub for this. You can show your support at [github-community/community/discussions/18230](https://github.com/github-community/community/discussions/18230). If enough people show their support, we might be able to support forks on GRS in the future.

Also, including results from repositories to which users contributed is one of the most requested features (see #1). #1122 adds this, but it is still under review.
