### ISSUE TITLE
Incorrect cache documentation

### ISSUE THREAD

**Issue by tinnamchoi** [anuraghazra/github-readme-stats#1888]
**Describe the bug**
The README first states on line 170 that the minimum is 1800 seconds (30 minutes), then on line 182 states that it is 2 hours.

**Expected behaviour**
Looking at the code, I'm pretty sure the latter is the correct one, and the former should be updated. 

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/101849050/181163374-9368fa41-fab6-4008-9ea9-91571198692e.png)

**Comment by tinnamchoi** [comment]
I also noticed that the minimum currently actually seems to be 4 hours, but only temporarily so I would suggest adding a line mentioning that.

**Comment by rickstaa** [comment]
Hey @tinnamchoi, thanks for your issue and the PRs. Improving the cache documentation is already on our roadmap (see #1760). @coderboy-exe is currently working on this issue. Since #1760 is more about the location of the cache documentation and #1889 and #1890 about errors in the cache documentation, I will merge your Prs. Thanks a lot for your contributions! 🎉

**Comment by rickstaa** [comment]
Closing since these improvements have been released in the main branch. @tinnamchoi, thanks again for your contributions!
