### ISSUE TITLE
Add all repositories card

### ISSUE THREAD

**Issue by dlvdls18** [anuraghazra/github-readme-stats#1905]
Just like pin, add a card for all repositories

**Comment by rickstaa** [comment]
@dlvdls18 Thanks for your feature request. I am, however, not entirely sure if I understand your feature request. Can you give an example of what information such a card would hold? Would it list all the repositories of a user? I think this would quickly become a relatively big card since many users have more than 100 repositories.

**Comment by dlvdls18** [comment]
Thanks for your understanding. I think instead of all repositories, how about top 5 repositories?

**Comment by rickstaa** [comment]
@dlvdls18 Ah, I see. Unfortunately, I don't think your feature will add anything new since you can use HTML to create a grid of repositories (see https://github.com/anuraghazra/github-readme-stats#quick-tip-align-the-repo-cards). I will close this feature request for now since I think it will complicate our codebase too much.  

I think adding the [card_width] can improve the process of creating a grid of 5 repositories is adding the [card_width](https://github.com/anuraghazra/github-readme-stats#language-card-exclusive-options) parameter to the repo card. Now the width is optimized for the GitHub readme, but with this feature, users will be better able to adjust the grid to their liking. Feel free to open a feature request for this feature.

```md

<div align="center">
<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats" />
</a>
<a href="https://github.com/anuraghazra/convoychat">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=convoychat" />
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats" />
</a>
<a href="https://github.com/anuraghazra/convoychat">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=convoychat" />
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats" />
</a>
<a href="https://github.com/anuraghazra/convoychat">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=convoychat" />
</a>
</div>
```


<div align="center">
<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats" />
</a>
<a href="https://github.com/anuraghazra/convoychat">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=convoychat" />
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats" />
</a>
<a href="https://github.com/anuraghazra/convoychat">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=convoychat" />
</a>
<a href="https://github.com/anuraghazra/github-readme-stats">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=github-readme-stats" />
</a>
<a href="https://github.com/anuraghazra/convoychat">
  <img align="center" src="https://github-readme-stats.vercel.app/api/pin/?username=anuraghazra&repo=convoychat" />
</a>
</div>
