### ISSUE TITLE
Refresshing when updates?

### ISSUE THREAD

**Issue by epsseniyer** [anuraghazra/github-readme-stats#1947]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by epsseniyer** [comment]
please make

**Comment by AspectOfJerry** [comment]
> please make

_Please make_ a more precise description of the problem. You managed to get the bug report template but now you have to fill it! That would surely help others better understand the situation.

Thank you.

**Comment by rickstaa** [comment]
@epsseniyer, I agree with @AspectOfJerry. Without giving any information, It's very hard to guess what this issue is about. I suspect it is because you want the card to update in real-time. If that is the case, you can [deploy your own Vercel](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance instance and remove the caching code:

https://github.com/anuraghazra/github-readme-stats/blob/4b6f4650b21a892b8ee1f57593b38efffed74155/api/index.js#L54-L58
