### ISSUE TITLE
[Feature] API for returning individual github status

### ISSUE THREAD

**Issue by madeindra** [anuraghazra/github-readme-stats#199]
**Is your feature request related to a problem? Please describe.**
I've been wanting to create my custom Github Status card instead of using the default card. To do that, I need to get the individual value of the GitHub status.

**Describe the solution you'd like**
The solution could be similar to what I did here: https://github.com/madeindra/github-readme-stats

**Describe alternatives you've considered**
No other than not using this feature.

**Additional context**
This is how I did with my solution but it's still crude and I'm not confident to do a PR.

I wrote the label using markdown and the values were generated by the API.

<img width="212" alt="Screen Shot 2020-07-26 at 5 32 19 PM" src="https://user-images.githubusercontent.com/42365530/88476880-f9ee1e00-cf65-11ea-8352-5120ff2928d4.png">

**Comment by nthnchu** [comment]
@madeindra Not sure if I understand your feature. Is it endpoints like /api/json/commits that return json or an endpoint that lets you enter svg markup and replaces [COMMITS] with the number of commits? Or is it something entirely different, like a new card design?

**Comment by madeindra** [comment]
@nthnchu Correct, there are separate svg files for each. e.g. one API return svg for commits.

**Comment by nthnchu** [comment]
The only thing I'm against is that the design is different than the normal stats card. The designs should look similar just to be consistent. Good idea, though. The other thing is there was a major refactor since your fork was created. If you could merge them at https://github.com/madeindra/github-readme-stats/compare/master...anuraghazra:master, that would be great! I'm also going to make some improvements in a PR if that's okay with you.

**Comment by madeindra** [comment]
@nthnchu Alright, I'll find a time later today to refine my fork, thanks for that

**Comment by rickstaa** [comment]
Closing in favour of #624.
