### ISSUE TITLE
Top Languages Card doesn't include my open source contributions

### ISSUE THREAD

**Issue by royrustdev** [anuraghazra/github-readme-stats#1994]
**Is your feature request related to a problem? Please describe.**

Top languages card doesn't include data from my pull-requests. It simply excludes my contributions in all fork repositories. 

**Describe the solution you'd like**

As the name suggests **Top Languages**, it should also include all `forked` repositories and measure accordingly. Therefore inclusion of data from `Pull Requests` are very crucial to determine **Top Languages**

**Describe alternatives you've considered**

I haven't found any alternatives yet! I tried to increase the `langs_count` but doesn't help. So I guess **new feature** is needed to solve this issue.

**Comment by rickstaa** [comment]
@royrustdevThanks for your feature request!

A PR was recently created to include the results of the fork (see #1803). It was, however, closed due to the current GraphQL implementation. Currently, the GraphQL API does not allow us to fetch language results for individual users. It only returns language results for repositories. As a result, the language card is already not showing the correct statistics. Adding support for forks would make this problem worse. The GraphQL API has to be extended to allow forks to be supported. I created a feature request with GitHub for this. You can show your support at [github-community/community/discussions/18230](https://github.com/github-community/community/discussions/18230). If enough people show their support, we might be able to support forks on github-readme-stats in the future.

Also, including results from repositories to which users contributed is one of the most requested features (see #1). #1122 adds this, but it is still under review.
