### ISSUE TITLE
Adding forks to lang stats

### ISSUE THREAD

**Issue by akielaries** [anuraghazra/github-readme-stats#2018]
I had gone down quite the rabbit hole from these here #505 and here #1108 trying to figure out how to add my forks to my language stats card on my profile. I ended up editing some existing javascript code specifically top-languages-fetcher.js and top-langs.js but wasn't able to get anything working that would show my forked repo's in the stats card. What is the proper way to implement a small feature like this? Has anyone done it successfully?

**Comment by rickstaa** [comment]
@akielaries Thanks for your feature request. This feature request has been requested multiple times in the past. Unfortunately, the current version of GraphQL API doesn't allow us to implement this feature stably. For an explanation on why this is the case, see my comment in https://github.com/anuraghazra/github-readme-stats/pull/1122#issuecomment-1152066225.

> Since the current [GraphQL languages object](https://docs.github.com/en/graphql/reference/objects#language) returns the languages used in a repository, not those in the commits done by a specific user, the current version of the PR will make the language stats less accurate. I created a feature request to improve this behaviour on GitHub's side (see https://github.com/orgs/github-community/discussions/18230). You can show your support there. 

If you don't care about language accuracy, you can change the GraphQL request in your own fork. This can be done by changing

https://github.com/anuraghazra/github-readme-stats/blob/192170c1111333a2a6a65015c81ab1cdb4b86a6a/src/fetchers/top-languages-fetcher.js#L17

to

````js
repositories(ownerAffiliations: OWNER, isFork: true, first: 100) {
```

**Comment by akielaries** [comment]
Thank you for the answer and pointing me to the right place!

**Comment by rickstaa** [comment]
> @rickstaa I have two questions about this.
> 
> 1. Does the inaccuracy in languages only apply to the included forks? Or will enabling forks also cause my own repos to have some level of inaccuracy?

The inaccuracy is caused because we can only fetch language stats by repository, not by user commit. Meaning that if you would enable the forks flag, all language results of all forks you created will also be counted towards your language stats (see https://github.com/anuraghazra/github-readme-stats/pull/1122#issuecomment-1152066225).

> 2. If we have a repo that is a fork, and make it a detached fork, will it then not be considered a fork by github-readme-stats?

I think a detached fork will be a separate repository and therefore will be considered in the current github-readme-stats. You can check this behaviour using the [GraphQL GitHub explorer](https://docs.github.com/en/graphql/overview/explorer) if you want (see https://github.com/anuraghazra/github-readme-stats/discussions/1770#language-card-related-questions).
