### ISSUE TITLE
Change text and change color graphic

### ISSUE THREAD

**Issue by Angelk90** [anuraghazra/github-readme-stats#221]
**Describe the solution you'd like**

Hi @anuraghazra 

1) It would be possible to implement the possibility of changing the texts of the cards, so the developer could also use the texts in his original language.

2) The ability to change the color of the statistics graph, both the color of the text inside it and the color of the colored part, instead of using the color of the title_color.

**Comment by anuraghazra** [comment]
> It would be possible to implement the possibility of changing the texts of the cards, so the developer could also use the texts in his original language.

Well good idea but it would mean users can also use any label they want and i wanted it to be consistent. (maybe i can do that by checking if each label has appropriate text)

> The ability to change the color of the statistics graph, both the color of the text inside it and the color of the colored part, instead of using the color of the title_color.

The color of rank circle? yes we can do that but i choose to do this way so that colors stay consistent throughout the card.

**Comment by Angelk90** [comment]
@anuraghazra : Are there any news?

**Comment by rickstaa** [comment]
Closed because I agree with @anuraghazra that it is better to keep the colour behaviour consistent.

@Angelk90 You can of course still open a new feature request for customization of the rank circle.  If there is enough support it could be we might reconsider but for now, this feature is not on our backlog.
