### ISSUE TITLE
Repositories contributed to is only the last year

### ISSUE THREAD

**Issue by vsoch** [anuraghazra/github-readme-stats#2269]
It looks like repositories contributed to is only the last year:

https://github.com/jstrieb/github-stats/issues/13

eg for mine, how could I have almost 700 but only have contributed to ~270? 

![85E07D40-532C-4FB0-AACF-6B216B4B318F](https://user-images.githubusercontent.com/814322/202885741-074a3277-b7dc-472c-a84b-7f67e004eb3a.jpeg)

I think this is still a good useful stat, but perhaps it should be made more obvious this is in the last year, because for most of the cards I’ve seen the number looks erroneously small. Maybe just “Contributed last year” or similar, or a mouse over information pop up that clarifies it?

Thanks for making this I really like having it in my profile!

**Comment by rickstaa** [comment]
@vsoch Thanks for bringing this error to our attention. I checked the GraphQL API in the [GraphQL explorer](https://docs.github.com/en/graphql/overview/explorer), and it seems that it only returns the contributions in the last year, while I would have expected the `repositoriesContributedTo.totalCount` to return all of a user's contributions.

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    name
    repositoriesContributedTo(
      contributionTypes: [COMMIT, ISSUE, PULL_REQUEST, REPOSITORY]
    ) {
      totalCount
    }
  }
}
```

```graphql
{
  "login": "vsoch"
}
```

I checked [the GraphQL](https://docs.github.com/en/graphql/reference/objects#user) documentation, and GitHub states the following:

> A list of repositories that the user **recently** contributed to.

They, unfortunately, don't elaborate on the meaning of **recently** but it seems to be the last year. This is in line with the period of the other GraphQL objects and was discussed in https://github.com/community/community/discussions/24350. 

I checked both GitHub's GraphQL and [Rest](https://docs.github.com/en/rest/search#search-issues-and-pull-requests) APIs, but I could not find an easy way to get all the repositories a user has contributed to. The only way I currently found for retrieving the total number of repositories a user has contributed to is looping through all years in the `contributionsCollection.totalRepositoriesWithContributedCommits` object via the `from` and `to` fields. 

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    name
    repositoriesContributedTo(
      contributionTypes: [COMMIT, ISSUE, PULL_REQUEST, REPOSITORY]
    ) {
      totalCount
    }
    contributionsCollection(from:"2020-11-20T15:45:00.000Z", to:"2021-11-20T15:45:00.000Z") {
      totalRepositoriesWithContributedCommits
    }
  }
}
```

This is similar to what is done in https://github.com/anuraghazra/github-readme-stats/pull/1691. Still, this solution is only feasible in self-deployed Vercel instances and the upcoming github action since, in the Public example, this change will likely trigger the GraphQL and Vercel rate/timeout limits. If you find a way, please let me know. I think, for now, the best we can do is:
- [ ] For the public Vercel instance, add a (last year) comment to the `Contributed to` item to prevent confusion. This is similar to what https://github.com/anuraghazra/github-readme-stats/blob/de4cefa0ad6826f1a378104b908dadf6c2f218c6/src/cards/stats-card.js#L137 proposes for the total commits item.
- [ ] Add a feature request to git https://github.com/community/community/discussions asking for an easy way to retrieve the total repositories a user has contributed to and update the documentation. For example, by adding date selectors (i.e. `from` and `to`) to the `repositoriesContributedTo` object. 
- [ ] Implement a function that loops through the years and sums the result of `repositoriesContributedTo.totalCount`. Release this feature under an env variable so people can enable it when they deploy their own Vercel instance (see https://github.com/anuraghazra/github-readme-stats/pull/2266 and https://github.com/anuraghazra/github-readme-stats/pull/2159 for an example).

I'm curious to hear your thoughts on this matter.

**Comment by vsoch** [comment]
I think it would take too many API calls with pagination to get that actual number, so my thinking is just to change the descriptor to describe what is actually being shown. E.g., instead of "Contributed to" something like "Contributed to since <last year>" or "Annual Contributions."

**Comment by rickstaa** [comment]
> I think it would take too many API calls with pagination to get that actual number, so my thinking is just to change the descriptor to describe what is actually being shown. E.g., instead of "Contributed to" something like "Contributed to since " or "Annual Contributions."

I double-checked my conclusion above, and it looks like the `contributionsCollection.totalRepositoriesWithContributedCommits` also includes a user's own repositories. It, therefore, is no option for retrieving the stats we want. I updated https://github.com/community/community/discussions/39589 to reflect this. Hopefully, GitHub will improve its GraphQL API, and we can show all repositories a user has contributed to for the private Vercel instance and the upcoming GitHub action. I agree that pagination for the Public instance will take too many requests and, therefore, will force the rate limits to be reached.

For now, I created #2274 to prevent the confusion from happening

#### Old card

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)
```

#### New card

[![Anurag's GitHub stats](https://github-readme-stats-git-fixrepo-7dd470-github-readme-stats-team.vercel.app/api?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats-git-fixrepo-7dd470-github-readme-stats-team.vercel.app/api?username=anuraghazra)](https://github.com/anuraghazra/github-readme-stats)
```

Let me know what you think. 🤔

**Comment by vsoch** [comment]
I think that's exactly what I had a mind, and a good solution until the API query can be figured out! :+1:

**Comment by rickstaa** [comment]
@vsoch Since your bug report highlighted a major error in the stats card, I merged #2274 without a review of @anuraghazra. It could be that @anuraghazra decides to revert this change, but I think it is justified. I created #2282 to track the accompanying feature request further. Hopefully, GitHub will update its API so that we can also show the total time contributed to stats.

**Comment by rickstaa** [comment]
I just added #2283 to fix a small bug introduced in https://github.com/anuraghazra/github-readme-stats/pull/2274.

**Comment by vsoch** [comment]
Fantastic! It's showing up in my profile - and I know it's not perfect, but it's so much more clear! So I think it's a good change until there is an accurate count for total repos (I am not sure I want to know, haha) :laughing: 
![image](https://user-images.githubusercontent.com/814322/203313236-6244173c-6ea3-42af-8d97-055b840c12c9.png)
