### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by aydinnyunus** [anuraghazra/github-readme-stats#2281]
### Describe the bug

I have been using these cards for over a year but there is a rate limit on my profile.

### Expected behaviour

It should not show any rate limit page.

### Screenshots / Live demo link

Take a look at [my profile](https://github.com/aydinnyunus).

**Comment by rickstaa** [comment]
@aydinnyunus The rate-limit problem is a known problem that is caused by rate limits set on GitHub's GraphQL API (see https://docs.github.com/en/graphql/overview/resource-limitations).  This issue is tracked at https://github.com/anuraghazra/github-readme-stats/issues/1471. I checked the cards, and the rate limit is no longer shown. 

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=aydinnyunus&random=random)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=aydinnyunus&random=random)](https://github.com/anuraghazra/github-readme-stats)
```

The best thing to do to prevent this error from happening is to deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance). 

I also created https://github.com/anuraghazra/github-readme-stats/pull/2159, which might release the PATs a bit, but this PR is still under review. Apart from that, we have to wait till @anuraghazra adds the new PATs I gave him since, currently, only one PAT is working (see https://github.com/anuraghazra/github-readme-stats/pull/2178).
