### ISSUE TITLE
Bug with username argument

### ISSUE THREAD

**Issue by IskIvanov** [anuraghazra/github-readme-stats#2285]
### Describe the bug

Hi, I noticed that my username does not render on the github preview readme.

"https://github-readme-stats.vercel.app/api?username=IskIvanov"

### Expected behaviour

To be able to see the readme stats on github preview

<img width="275" alt="Screenshot 2022-11-22 at 16 42 20" src="https://user-images.githubusercontent.com/28646980/203357445-51311894-e0ce-49f1-b8ba-18aba5408290.png">

### Screenshots / Live demo link

<img width="581" alt="Screenshot 2022-11-22 at 16 31 43" src="https://user-images.githubusercontent.com/28646980/203354748-84e1a5e9-6707-417c-b98d-76abfcc1647a.png">

**Comment by rickstaa** [comment]
@IskIvanov Thanks for the bug report. It is caused by GitHub's rate limit see #1471. Not much we can do about it other than updating PATs. 🤔  If you want to prevent this issue from happening, you should deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance). 👍🏻
