### ISSUE TITLE
Estou com um problema no meu read.me e a variável PAT_1!!

### ISSUE THREAD

**Issue by 0Marx0** [anuraghazra/github-readme-stats#2287]
### Describe the bug

Estava organizando meu perfil aqui no GitHub e gosto sempre de seguir tudo na paleta "Radical". Porém, no meu "GitHub Stats" como a aparecer o problema "Maximum retries exceeded; Please add an env variable called PAT_1 with your github token in vercel". Não faço ideia do que poderia ser e como concertar para continuar usando a paleta que gosto. Procurei em alguns locais sobre mas ainda não ficou claro.

### Expected behaviour

Que alguém me explique como posso proceder com o problema para poder aprender mais.

**Comment by MitkoVtori** [comment]
O problema é muito comum. As pastas precisam reiniciar ou algo assim. Geralmente não leva mais de uma hora, então é só esperar que o problema será resolvido.

**Comment by rickstaa** [comment]
@0Marx0 The rate-limit problem is a known problem that is caused by rate limits set on GitHub's GraphQL API (see https://docs.github.com/en/graphql/overview/resource-limitations).  This issue is tracked at https://github.com/anuraghazra/github-readme-stats/issues/1471. I checked the cards, and the rate limit is no longer shown. 

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=0Marx0&random=random)](https://github.com/anuraghazra/github-readme-stats)

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=0Marx0&random=random)](https://github.com/anuraghazra/github-readme-stats)
```

The best thing to prevent this error from happening is to deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own-vercel-instance). 

I also created https://github.com/anuraghazra/github-readme-stats/pull/2159, which might release the PATs a bit, but this PR is still under review. Apart from that, we have to wait till @anuraghazra adds the new PATs I gave him since, currently, only one PAT is working (see https://github.com/anuraghazra/github-readme-stats/pull/2178).
