### ISSUE TITLE
Stats are not updating.

### ISSUE THREAD

**Issue by Imnaseli** [anuraghazra/github-readme-stats#2413]
### Describe the bug

my stats refuse to get updated, such as commit count.

**Comment by himanshu-dxm** [comment]
Change the src url from "https://github-readme-stats.vercel.app" to "https://github-readme-stats-ruby-one.vercel.app"

**Comment by qwerty541** [comment]
> found the solution: changing the theme will update the stats

Hey @moemnml33 

Changing theme works because any changes in URL query string parameters breaking the cache, but after that the card will be cached againg. You don't want to change theme each time to update stats, right? Therefore it is not a solution.

The default cache time on our public deployment is 6 hours. We use caching to decrease consumption of GitHub API tokens points in order to avoid public deployment downtimes. This measure is neccesary because GitHub API tokens limited by 5000 points per hour. If you want your card to be updated more often you can [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#on-vercel) using your own GitHub API token and set there any cache time using `CACHE_SECONDS` environment variable. That would be best solution.
