### ISSUE TITLE
count_private query parameter not workig for top languages in private deployments

### ISSUE THREAD

**Issue by mishankov** [anuraghazra/github-readme-stats#2437]
### Describe the bug

If `count_private` is set to `false` it looks like private repos are still in the statistics

### Expected behaviour

If `count_private` is set to `false` private repos are not in the statistics

**Comment by ritachien** [comment]
It seems `count_private` option is only for "Stats Card" in README. If you don't want to count on private repo lang, maybe you could try `exclude_repo` option! 

I'm on the opposite situation of you. Want to count the private repo lang but fail :confused:

**Comment by Zo-Bro-23** [comment]
You're right; the [lang fetcher](https://github.com/anuraghazra/github-readme-stats/blob/master/src/fetchers/top-languages-fetcher.js) doesn't have a `count_private` option. This is likely due to a GitHub limitation, since they are unlikely to allow access to any stats (like language stats) for a private repo. I might be wrong though, so @rickstaa feel free to correct me (or close this issue if I'm right!).

**Comment by rickstaa** [comment]
> You're right; the [lang fetcher](https://github.com/anuraghazra/github-readme-stats/blob/master/src/fetchers/top-languages-fetcher.js) doesn't have a `count_private` option. This is likely due to a GitHub limitation, since they are unlikely to allow access to any stats (like language stats) for a private repo. I might be wrong though, so @rickstaa feel free to correct me (or close this issue if I'm right!).

Your right. The reason is a general limitation in the GraphQL API or how GitHub works. Where for the stats, the query also includes a [restrictedContributionsCount](https://docs.github.com/en/graphql/reference/objects) which contains the private commits total when users decide to share this on their profile the language query doesn't show private data unless you have permission to read this data. 👍🏻

**Comment by rickstaa** [comment]
As implementing this feature without a change to the GraphQL API is too cumbersome I will close this issue for now.
