### ISSUE TITLE
Cards not showing on my profile

### ISSUE THREAD

**Issue by juletx** [anuraghazra/github-readme-stats#2499]
### Describe the bug

Cards are not showing on my profile: [https://github.com/juletx](https://github.com/juletx). Cards are shown correctly when I edit the readme locally. They are also shown correctly in this message and if I open the link on a new tab.

### Screenshots / Live demo link

[![GitHub Stats](https://github-readme-stats.vercel.app/api?username=juletx&show_icons=true&count_private=true&include_all_commits=true&theme=dracula&custom_title=GitHub%20Stats)](https://github-readme-stats.vercel.app/api?username=juletx&show_icons=true&count_private=true&include_all_commits=true&theme=dracula&custom_title=GitHub%20Stats)

**Comment by mkredzel** [comment]
Hi @juletx,

Looking at your profile I can see an issue with `custom_title` param. 

It needs to be URI-escaped:

-  `Top%20Languages` instead of `Top Languages`
-  `GitHub%20Stats` instead of `GitHub Stats`
- `Weekly%20Top%20Languages` instead of  `Weekly Top Languages`

<img src="https://github-readme-stats.vercel.app/api/top-langs/?username=juletx&layout=compact&langs_count=10&theme=dracula&custom_title=Top%20Languages">

<img src="https://github-readme-stats.vercel.app/api?username=juletx&show_icons=true&count_private=true&include_all_commits=true&theme=dracula&custom_title=GitHub%20Stats">

<img src="https://github-readme-stats.vercel.app/api/wakatime?username=juletxara&layout=compact&langs_count=10&theme=dracula&custom_title=Weekly%20Top%20Languages">

I hope that helps

**Comment by klpranaav** [comment]
**Describe the bug**
My stats Cards are not showing on my profile: https://github.com/klpranaav

**Expected behaviour**
No response

Screenshots / Live demo link
![image](https://github.com/anuraghazra/github-readme-stats/assets/99110613/03ae42a8-51cb-4d4e-a768-b53c70ec0ca1)

**Comment by qwerty541** [comment]
> **Describe the bug** My stats Cards are not showing on my profile: https://github.com/klpranaav and my streaks are not shown
> 
> **Expected behaviour** No response
> 
> Screenshots / Live demo link ![image](https://private-user-images.githubusercontent.com/99110613/299778501-03ae42a8-51cb-4d4e-a768-b53c70ec0ca1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNTg0MjAsIm5iZiI6MTcwNjI1ODEyMCwicGF0aCI6Ii85OTExMDYxMy8yOTk3Nzg1MDEtMDNhZTQyYTgtNTFjYi00ZDRlLWE3NjgtYjUzYzcwZWMwY2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA4MzUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2NTU5ZDkzZGFlNWFhZTNkMzgxNjVhNTUyMWEzYzA1OGJjNjAwOTcxOTAzOTQyMzViM2U5OTA5ZjNiMzhmMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9jSOL0OYYpMo6gb35bRWj0z4ERqnNEdh0OArXSj2IIY)

Answered your question there https://github.com/anuraghazra/github-readme-stats/discussions/3617?converting=1#discussioncomment-8253949
