### ISSUE TITLE
[Bug] Stat card private content wrong number of PRs

### ISSUE THREAD

**Issue by icandac** [anuraghazra/github-readme-stats#2621]
### Describe the bug

There occurs an error in the statcard when the "count_private=true" option is included. I know my number of commits and PRs. 

Number of commits is close to the actual number, but I guess it misses some commits as well, but Total number of PRs is %100 wrong. It shows here 1 for me for the last 3.5 half months but I at least opened 20 of them, and also my badge corrects me. 

I don't know with which API the private commits are taken but there is an issue with that for sure.

### Expected behaviour

I expect to see the correct number of PRs on the stat-card (and maybe for the commits as well).

### Screenshots / Live demo link

![image](https://user-images.githubusercontent.com/8245553/232918760-5de4aa46-08ef-4245-bb9e-384f5ba1191a.png)

![image](https://user-images.githubusercontent.com/8245553/232918856-b1c683fb-3a57-41e4-ad99-4c5ea7e237e0.png)

**Comment by Furkan-Ozdemir** [comment]
I have the same issue. I think it doesn't count private repo prs

**Comment by icandac** [comment]
> I have the same issue. I think it doesn't count private repo prs

I later noticed that it does, indeed. But it is still a bug since it just considers the PRs after the stat card is created.

**Comment by akshayaureatelabs** [comment]
@icandac @Furkan-Ozdemir Hello,

The bug you described is related to the statcard when the `"count_private=true"` option is included. The expected behavior is to see the correct number of PRs on the stat-card, and possibly the correct number of commits as well. Currently, the number of commits is close to the actual number, but it may miss some commits, and the total number of PRs is 100% wrong.

It appears that the `API` used to fetch private commits is causing the issue. The `API` may not be able to retrieve all the private commits and PRs, resulting in an inaccurate count on the stat-card.

To fix this bug, you may need to investigate the `API` used to fetch the private commits and PRs, and see if there are any limitations or issues with it. You may also want to check if there are any alternative `APIs` that can be used to fetch the private commits and PRs. Once you have identified the issue, you can work on updating the code to ensure that the correct number of PRs and commits are displayed on the stat-card.

**Comment by rickstaa** [comment]
> @icandac @Furkan-Ozdemir Hello,
> 
> The bug you described is related to the statcard when the `"count_private=true"` option is included. The expected behavior is to see the correct number of PRs on the stat-card, and possibly the correct number of commits as well. Currently, the number of commits is close to the actual number, but it may miss some commits, and the total number of PRs is 100% wrong.
> 
> It appears that the `API` used to fetch private commits is causing the issue. The `API` may not be able to retrieve all the private commits and PRs, resulting in an inaccurate count on the stat-card.
> 
> To fix this bug, you may need to investigate the `API` used to fetch the private commits and PRs, and see if there are any limitations or issues with it. You may also want to check if there are any alternative `APIs` that can be used to fetch the private commits and PRs. Once you have identified the issue, you can work on updating the code to ensure that the correct number of PRs and commits are displayed on the stat-card.

@akshayaureatelabs thank you so much for answering this question🙏🏻! To add to your answer, the `count_private` variable regards the commits and only works if people share their private contributions to their profile. A discussion on why this variable is confusing and should be deprecated is found in https://github.com/anuraghazra/github-readme-stats/issues/2517.

**Comment by rickstaa** [comment]
@icandac the best way to get the most accurate results is to deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own). More accurate results will be possible when the GitHub action is released (see https://github.com/anuraghazra/github-readme-stats/issues/2179).
