### ISSUE TITLE
[Feature Request] Counting private repos for the language card

### ISSUE THREAD

**Issue by icandac** [anuraghazra/github-readme-stats#2622]
### Is your feature request related to a problem? Please describe.

As we know of, there is count_private option for the stat cards. I can not be the first one who think of adding that as a method for the language cards, am I?

### Describe the solution you'd like

I didn't check the repo but the method can be added easily to the language card class, if the structure consists classes.

### Describe alternatives you've considered

the classes and their structures can be different for sure but there should be a way to put count_pricate as far as it is not an issue getting the pricate contributions by an api call.

**Comment by Kyu** [comment]
+1 cause I want this as well. I believe this would require giving the app access to your gh account, I'm not familiar with the codebase but its a project I'd want to take on this summer if possible

**Comment by rickstaa** [comment]
> +1 cause I want this as well. I believe this would require giving the app access to your gh account, I'm not familiar with the codebase but its a project I'd want to take on this summer if possible.
> 
> Edit: seems to already be a feature if hosted locally, #2515

@Kyu is correct, this feature is available when you deploy [your own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) or the [unreleased GitHub action](https://github.com/anuraghazra/github-readme-stats/issues/2179). We cannot implement it on the public instance since we don't have permissions to retrieve stats about your public repositories. The reason that we have `include_private` for the stats card is that users can decide to share their private contributions to their profile using the GitHub interface (see https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-settings-on-your-profile/showing-your-private-contributions-and-achievements-on-your-profile). There however is a feature request to remove that option since it contains the contributions and not the commits (see https://github.com/anuraghazra/github-readme-stats/issues/2517).
