### ISSUE TITLE
C#

### ISSUE THREAD

**Issue by Progamer1251718** [anuraghazra/github-readme-stats#2624]
### Is your feature request related to a problem? Please describe.

Can you Add C# to the code?

**Comment by qwerty541** [comment]
I don't understand what exactly do you mean. If you mean adding C# to the Top languages card, it is already there. See: https://github.com/anuraghazra/github-readme-stats/blob/master/src/common/languageColors.json#L63

**Comment by rickstaa** [comment]
> I don't understand what exactly do you mean. If you mean adding C# to the Top languages card, it is already there. See: https://github.com/anuraghazra/github-readme-stats/blob/master/src/common/languageColors.json#L63

@qwerty541 thanks for answering this question. You are right, C# is already supported by [the upstream](https://github.com/github/linguist).

**Comment by rickstaa** [comment]
@Progamer1251718 I will close this issue since I cannot reproduce it. I checked the [GraphQL explorer](https://docs.github.com/en/graphql/overview/explorer) and your profile does not return any repositories with `C#` in them. If you are sure you have coded in C# it could be that the commits that contain that code are in private repositories. For your private stats to show up, you have to deploy your own Vercel instance (see https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own). Alternatively, you could have more than 100 repositories and the results are not included because we currently only fetch the first 100 repositories (see https://github.com/anuraghazra/github-readme-stats/issues/1801 for more information).

```graphql
query userInfo($login: String!) {
  user(login: $login) {
    # fetch only owner repos & not forks
    repositories(ownerAffiliations: OWNER, isFork: false, first: 100) {
      nodes {
        name
        languages(first: 10, orderBy: {field: SIZE, direction: DESC}) {
          edges {
            size
            node {
              color
              name
            }
          }
        }
      }
    }
  }
}
```

```graphql
{"login": "Progamer1251718"}
````
