### ISSUE TITLE
Cached language stats

### ISSUE THREAD

**Issue by pandasoli** [anuraghazra/github-readme-stats#2638]
### Describe the bug

When I access [the top langs for my profile](https://github-readme-stats.vercel.app/api/top-langs/?username=pandasoli) it shows I have 96.96% of **Python** code, and 0.75% of **Go** code, what is "not true" (not based on numbers) because I have about 3 or 2 SMALL **Python** repos and a lot of kinda big **Go** repos (enough to be more than **Python**).

### Expected behaviour

About 5 or 10% of **Python** code, and about 70 or 80% of **Go** code.

### Screenshots / Live demo link

![Current state of the stats](https://user-images.githubusercontent.com/76575902/234020812-b21ee274-1946-429b-a4d4-47fd4710c3fb.PNG)

## Repos count

![3 **Python** repos](https://user-images.githubusercontent.com/76575902/234020815-8345fbe0-8563-47c7-a9c6-c6ce7bfe9dce.PNG)
![10 **Go** repos](https://user-images.githubusercontent.com/76575902/234020806-612b7a32-cb50-42cc-bf65-914cb522d9b0.PNG)

### Additional context

I also tried to delete all the **Python** repos, so I would have no **Python** code in my profile (later I can restore them), I tried filter my repos by **Python** and there was none, perfect, but looking at the link again, nothing changed, and yes I tried clearing my browser cache.

And about [anuraghazra/github-readme-stats#136](https://github.com/anuraghazra/github-readme-stats/issues/136#issuecomment-665164174), as I said if we sum the bytes of the **Python** repos it is gonna be smaller than the Go repos (I guess based on my knowledge because I coded them).

**Comment by rickstaa** [comment]
@pandasoli due to GraphQL limitations, we are unable to improve the language results 😅. More information about this can be found in https://github.com/anuraghazra/github-readme-stats/issues/1801. I created a feature request at https://github.com/orgs/community/discussions/18230 to improve this behaviour. You can show your support there. The results will be somewhat improved when the [GitHub action](https://github.com/anuraghazra/github-readme-stats/issues/2179) is released. Further, https://github.com/anuraghazra/github-readme-stats/pull/1732 is currently under review which allows users to rank the used languages based on the repositories they are used in.  Maybe you can try out this pull request and see if it improves the results 🤔?
