### ISSUE TITLE
Top Languages not showing external contributions anymore

### ISSUE THREAD

**Issue by daniCh8** [anuraghazra/github-readme-stats#264]
**Describe the bug**
After the [feat: improved top lang fetching & changed title](https://github.com/anuraghazra/github-readme-stats/commit/826f0201aaf5c4c2c9c5aa19690c9b7e5b05d5b1#diff-c5271cc08cad89e62ca28835d21b07a1) commit, _top languages_ doesn't take into account the code written in shared project, but only the code written in owned repositories. 

**Expected behavior**
In Github (and in general in Software Development) projects are rarely done alone. So I think it would be better when counting the language percentage to take into account also the code written in projects shared with other profiles, like github-readme-stats was doing at the beginning.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
I have noticed this issue because I did a big shared Java project for my Bachelor Thesis, and I wasn't seeing its contribution in the Languages table anymore. Here is the language table as it is now:

![](https://camo.githubusercontent.com/817446deee4ca847471548401cba3b3853f210f0/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170692f746f702d6c616e67732f3f757365726e616d653d64616e6943683826686964653d5648444c)

And here is (veeeery roughly, since I didn't have a screenshot of it before the update and I edited the picture above to do this) how it used to be:

![](https://svgshare.com/i/NNC.svg)

As you can see, it changes severely - and I think many other GitHub users have their code contributions not only on their owned repositories.

**Additional context**
...maybe you can add it as a feature in the call?  Something like ```&fetch=owned``` or ```&fetch=all``` to distinguish between the two.

Thanks in advance!

**Comment by HPaulson** [comment]
Was noticing this as well, but assumed it was a bug... It won't show shared repos, or even repos you're the only contributor to, just under an organization. I don't think it's possible with the API, but the ideal situation would be to use the langs from each of your commit, rather than the full project.... However if this is not possible (Which i'm sure it's not), I would definitely have an additional option as you suggested, but I'd recommend only taking into account repos you have committed to, not just ones that are shared.

**Comment by mchelen-gov** [comment]
noticed this issue as well, causing my top langs to be blank: https://github.com/mchelen-gov/mchelen-gov
