### ISSUE TITLE
No community github stars

### ISSUE THREAD

**Issue by ManiMozaffar** [anuraghazra/github-readme-stats#2653]
### Describe the bug

While other plugins are able to detect community related github star, this repo is not.
When a repo is moved to a community, this repo cannot count it as star.

### Expected behaviour

To count self created repo that is given ownership to a community.

**Comment by rickstaa** [comment]
@ManiMozaffar This is our most requested feature (see https://github.com/anuraghazra/github-readme-stats/issues/1). The reason we don't include them is because of some limitations in the GitHub GraphQL API. You can, however, already use this feature on your own Vercel instance  (see https://github.com/anuraghazra/github-readme-stats/pull/1122 and https://github.com/anuraghazra/github-readme-stats/pull/2459). We will make this feature available for the upcoming GitHub action version, since the GraphQL limitations don't apply there (see https://github.com/anuraghazra/github-readme-stats/issues/2179).
