### ISSUE TITLE
Waka time card broken range parameter broken

### ISSUE THREAD

**Issue by rickstaa** [anuraghazra/github-readme-stats#2698]
### Describe the bug

It looks like the `range` parameter of the WakaTime card is no longer working due to some upstream changes. https://github.com/anuraghazra/github-readme-stats/pull/2670 fixed the card for the `all_time` range. For the other ranges, however, the 403 "Forbidden" error is thrown. The strange thing is that this error is not thrown when I directly try the generated WakaTime API link in the browser, but it only happens when I request it through Axios. This is strange as according to the documentation this should work.

https://github.com/anuraghazra/github-readme-stats/blob/688f4e497593d22d813423248bd96aaf0f0e495f/src/fetchers/wakatime-fetcher.js#L14-L20

**Regular card**

[![willianrod's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Harlok&layout=compact)](https://github.com/anuraghazra/github-readme-stats)

```md
[![willianrod's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Harlok&layout=compact)](https://github.com/anuraghazra/github-readme-stats)
```

***All time**

[![willianrod's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Harlok&layout=compact&range=all_time)](https://github.com/anuraghazra/github-readme-stats)

```md
[![willianrod's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Harlok&layout=compact&range=all_time)](https://github.com/anuraghazra/github-readme-stats)
```

**Last 7 days**

[![willianrod's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Harlok&layout=compact&range=last_7_days)](https://github.com/anuraghazra/github-readme-stats)

```md
[![willianrod's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Harlok&layout=compact&range=last_7_days)](https://github.com/anuraghazra/github-readme-stats)
```

**Last 30 days**

[![willianrod's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Harlok&layout=compact&range=last_30_days)](https://github.com/anuraghazra/github-readme-stats)

```md
[![willianrod's wakatime stats](https://github-readme-stats.vercel.app/api/wakatime?username=Harlok&layout=compact&range=last_30_days)](https://github.com/anuraghazra/github-readme-stats)
```

### Expected behaviour

Should work according to the documentation

**Comment by rickstaa** [comment]
Maybe an access token is needed with the new API (see https://wakatime.com/developers#authentication). If somebody wants to tackle this, be my guest. It could be that the new API requires a API token (see https://wakatime.com/developers#authentication).

**Comment by rickstaa** [comment]
It looks that for some users, the solution by @fabianocouto still doesn't fix their card. For example, the user in https://github.com/anuraghazra/github-readme-stats/issues/1348 does have a public profile and the stats can be requested through the browser but through Axios something is broken:

https://wakatime.com/@AbhJ

https://wakatime.com/api/v1/users/AbhJ/stats/all_time?is_including_today=true

**Comment by hakula139** [comment]
> It looks that for some users, the solution by @fabianocouto still doesn't fix their card. For example, the user in #1348 does have a public profile and the stats can be requested through the browser but through Axios something is broken:
> 
> https://wakatime.com/@AbhJ
> 
> https://wakatime.com/api/v1/users/AbhJ/stats/all_time?is_including_today=true

It is related to the user's settings [here](https://wakatime.com/settings/profile) (Display code time publicly). If you select `Last 7 Days`, then

<https://wakatime.com/api/v1/users/Hakula/stats/all_time?is_including_today=true>

is forbidden, no matter requesting through a browser or Axios, without authentication (like an access token), but

<https://wakatime.com/api/v1/users/Hakula/stats/last_7_days?is_including_today=true>

is still fine, since it's public.

It might be related to some WakaTime API changes, making the first link inaccessible as the settings suggests (only last 7 days are made public), but still allowing public access to the second one.

**Comment by rickstaa** [comment]
> https://wakatime.com/api/v1/users/Hakula/stats/all_time?is_including_today=true

Thanks for looking into this issue 🚀. I checked the behaviour you described, and it seems to be correct. The new API behaviour is that if users are logged in, they can request all ranges from the API in the browser. If they are logged out or try to request stats from other users, they can only request the time range that is used on the profile. I think there are two ways to solve the behaviour:

- We document this in the documentation.
- We implement some kind of loop that tries the three options ("all time", "last_7_days" and "last_year") and updates the card tile based on that.

What option do you guys think is best?

**Comment by hakula139** [comment]
From my perspective, first document this behavior in the documentation, recommending users to explicitly specify the `range` parameter according to their settings. Then to make it compatible with the former API, we implement some kind of loop if the user left it blank.

**Comment by rickstaa** [comment]
> From my perspective, first document this behavior in the documentation, recommending users to explicitly specify the `range` parameter according to their settings. Then to make it compatible with the former API, we implement some kind of loop if the user left it blank.

@hakula139 I just implemented https://github.com/anuraghazra/github-readme-stats/pull/2707 which automatically gets the right information, throws descriptive errors and documents the behaviour in the README. I would appreciate it if you could review this PR so that we can merge. I don't use the WakaTime card myself, so a review of somebody who does would be great!

**Comment by alanhamlett** [comment]
You can check the range for a user with https://wakatime.com/api/v1/users/current looking at the user's attribute `public_profile_time_range`.

**Comment by XaaRii** [comment]
I had a problem with my wakatime card as well and couldn't fix it no matter what i tried. Then i visited the wakatime profile settings page and found out i had selected 'last 14 days' (as a free user), which is apparently not for free anymore. Changing it to last 7 days fixed it.
(used url: `https://github-readme-stats.vercel.app/api/wakatime?username=Pawele&theme=dark&range=last_year&is_including_today=true`)


also (not related to the problem), i noticed that wakatime api call return different time values on my machine and on different machines (shows less time spent). It almost feels like it hides time stats from private repos, but I haven't really worked on any since i started using it.
Any ideas why would that be?
(used url: https://wakatime.com/api/v1/users/Pawele/stats/last_year?is_including_today=true)
_also, somehow 'last_7_days' (publicly) is forbidden for me while 'last_year' (publicly) isn't..._

**Comment by rickstaa** [comment]
> I had a problem with my wakatime card as well and couldn't fix it no matter what i tried. Then i visited the wakatime profile settings page and found out i had selected 'last 14 days' (as a free user), which is apparently not for free anymore. Changing it to last 7 days fixed it. (used url: `https://github-readme-stats.vercel.app/api/wakatime?username=Pawele&theme=dark&range=last_year&is_including_today=true`)
> 
> also (not related to the problem), i noticed that wakatime api call return different time values on my machine and on different machines (shows less time spent). It almost feels like it hides time stats from private repos, but I haven't really worked on any since i started using it. Any ideas why would that be? (used url: https://wakatime.com/api/v1/users/Pawele/stats/last_year?is_including_today=true) _also, somehow 'last_7_days' (publicly) is forbidden for me while 'last_year' (publicly) isn't..._

The card will automatically fetch the right range after https://github.com/anuraghazra/github-readme-stats/pull/2707 is merged.

**Comment by alanhamlett** [comment]
[Last 14 Days](https://wakatime.com/dashboard?preset=Last%2014%20Days) is still free so it's probably something else causing that issue.

**Comment by XaaRii** [comment]
> [Last 14 Days](https://wakatime.com/dashboard?preset=Last%2014%20Days) is still free so it's probably something else causing that issue.
 
On dashboard it is still free and functional, yes. But in `Settings > Preferences > Default Range` things starts to get funny. When I pick 'Last 14 days' here, nothing seems to be wrong, but it's just not working.  Once you select something else (even just 'Last week' that still fits into 'Last 14 days' timeframe), red text pops up saying "You need a [premium](https://wakatime.com/pricing) account for more than the last 7 days."
Judging by the nonfunctional 'last_14_days' api parameter timerange, this is either obsolete or unfinished feature. Not sure where to report it though...
 
> Could be related to [public vs private keystroke timeout](https://wakatime.com/faq#leaderboard-vs-dashboard) if you've changed your private one.

Thanks for pointing it out! I didn't notice it before, but the timeout field really has a different value.

**Comment by alanhamlett** [comment]
> Judging by the nonfunctional 'last_14_days' api timerange parameter, this is either obsolete or unfinished feature. Not sure where to report it though...

There's two different ranges: (1) dashboard ranges and (2) stats ranges. Dashboard ranges are case sensitive, include spaces, and work for the Summaries, Durations, and Heartbeats api endpoints. Stats ranges are lowercase and use underscores instead of spaces. They only work on the Stats and Insights api endpoints.

The dashboard has the `Last 14 Days` range, but there never was a `last_14_days` range for Stats.

Can you send a video showing how to reproduce the red text error to support@wakatime.com? Loom.com is a good tool for creating the video.

**Comment by XaaRii** [comment]
I understand there are two different ranges, but I don't understand which one is affected by the [Preferences settings](https://wakatime.com/settings/preferences) - because there are settings that clearly affects both (eg. Keystroke timeout).

To avoid any more misunderstanding, [here is a video of what i meant (with that red text warning)](https://www.veed.io/view/380a0aee-4db8-4e81-9fbd-d46ce6949032?panel=share).

> Can you send a video showing how to reproduce the red text error to support@wakatime.com?

Sure, I can do that.

**Comment by hiyorijl** [comment]
> I had a problem with my wakatime card as well and couldn't fix it no matter what i tried. Then i visited the wakatime profile settings page and found out i had selected 'last 14 days' (as a free user), which is apparently not for free anymore. Changing it to last 7 days fixed it. (used url: `https://github-readme-stats.vercel.app/api/wakatime?username=Pawele&theme=dark&range=last_year&is_including_today=true`)
> 
> also (not related to the problem), i noticed that wakatime api call return different time values on my machine and on different machines (shows less time spent). It almost feels like it hides time stats from private repos, but I haven't really worked on any since i started using it. Any ideas why would that be? (used url: https://wakatime.com/api/v1/users/Pawele/stats/last_year?is_including_today=true) _also, somehow 'last_7_days' (publicly) is forbidden for me while 'last_year' (publicly) isn't..._

thanks this fixed it
