### ISSUE TITLE
Git hub stats with the wrong score letter?

### ISSUE THREAD

**Issue by PedroHGaspar** [anuraghazra/github-readme-stats#2751]
### Describe the bug

![image](https://github.com/anuraghazra/github-readme-stats/assets/37162818/7e529d4c-15dd-46ad-ad1a-72b8d459eec8)

Basically i had A+ yesterday, and today after tat PAT_1 being reset, i'm wit the B score. Is this a bug? Is there anything that i can do to have my score back?

**Comment by Mmeckawy** [comment]
Same here but then I checked the files and someone changed the grading system

**Comment by Mmeckawy** [comment]
> > Same here but then I checked the files and someone changed the grading system
> 
> Really? What do we do now? Like, the gradings are now that high?

I think it's a bit unfair honestly because we used to be in the top 60% but according to the new system we are in the bottom 25% so it does not make any sense

**Comment by PedroHGaspar** [comment]
> > > Same here but then I checked the files and someone changed the grading system
> > 
> > 
> > Really? What do we do now? Like, the gradings are now that high?
> 
> I think it's a bit unfair honestly because we used to be in the top 60% but according to the new system we are in the bottom 25% so it does not make any sense

It's really unfair, but i thought it was a bug... Well, i think we don't have so much to do about that. :(

**Comment by rickstaa** [comment]
@PedroHGaspar, @Mmeckawy I decided to merge https://github.com/anuraghazra/github-readme-stats/pull/2749 since an improvement has been requested by many people. As explained in that issue, the old ranking function almost everybody A+ and made it nearly impossible to get a higher or lower ranking :sweat_smile:. As a result, @francois-rozet proposed a new ranking version that is more well-balanced and motivates people to contribute to OS project and follow good code practices. I know that it will not make everybody happy, but in my opinion, it results in a better ranking scheme.

Having that said, creating a good ranking scheme is hard when we don't have the ground truth mean of all developers on GitHub. As a result, the ranking mechanism is still open to change and therefore, feel free to suggest any improvements to the weights or calculation function in #455 🙏🏻.

**Comment by Mmeckawy** [comment]
@rickstaa Tank you for the clarification. I agree with the point that a lot of people were getting A+ althought some contributed way more than others and I believe the new system will motivate us to keep working on ourselves and explore new projects.

**Comment by rickstaa** [comment]
> @rickstaa Thank you for the clarification. I agree with the point that a lot of people were getting A+ althought some contributed way more than others and I believe the new system will motivate us to keep working on ourselves and explore new projects.

Great! However, don't hesitate to comment on #455 if you find ranking up is too hard 👍🏻.
