### ISSUE TITLE
The card doesn't show all my commits and pr's

### ISSUE THREAD

**Issue by PigeonTheDev** [anuraghazra/github-readme-stats#2768]
### Describe the bug

The card describes that Ihave 0 pr's even though I opened 10 prs just  last week, And I' sure I don't have just 30 commits

**Comment by qwerty541** [comment]
The card shows correct data because by default it show only your public contributions. I consider that 10 PRs you are talking about are private contributions. To show your private contributions on stats card you should [deploy your own vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) using your own GitHub API token which allowed to see your private data.
