### ISSUE TITLE
Full progress circle should be unbroken

### ISSUE THREAD

**Issue by silverwind** [anuraghazra/github-readme-stats#2838]
### Describe the bug

Full progress circle shows a slight break in top center, which is a bit ugly.

### Expected behavior

No break in full circle.

### Screenshots / Live demo link

<img width="237" alt="image" src="https://github.com/anuraghazra/github-readme-stats/assets/115237/707f25a0-2cb9-4ff5-9c06-834bc9ba41c8">

<picture>
  <source
    srcset="https://github-readme-stats.vercel.app/api?username=silverwind&theme=dark&hide_border=true&show_icons=true&bg_color=00000000"
    media="(prefers-color-scheme: dark)"
  />
  <source
    srcset="https://github-readme-stats.vercel.app/api?username=silverwind&hide_border=true&show_icons=true&bg_color=00000000"
    media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
  />
  <img src="https://github-readme-stats.vercel.app/api?username=silverwind&hide_border=true&show_icons=true&bg_color=00000000"/>
</picture>

**Comment by rickstaa** [comment]
@silverwind first congrats on achieving the full circle 🚀! I agree it should be a full circle when people are truly at 100%. You are welcome to create a pull request for me to review and merge :+1:.

**Comment by silverwind** [comment]
I guess one fix would be to raise the maximum `stroke-dasharray` from `250` to `252` which fully fills the circle for me.

**Comment by rickstaa** [comment]
> [silverwind](/silverwind)

I think if it needed fixing, it would be at:

https://github.com/anuraghazra/github-readme-stats/blob/1997328951ac458a14bdf264266913e3f1d02575/src/getStyles.js#LL32C9-L32C65

You could, for example, set a condition that  >`99`% is displayed as `100`%. However, I think the current behaviour is correct since you are at `99.09499154691616`%, and your stat can still grow. You can see this by looking at @anuraghazra's stat, which, when you set `include_all_commits=true`, is at `99.79728062476163`%, which displays as a complete circle.

```md
[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)
```

[![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&include_all_commits=true)](https://github.com/anuraghazra/github-readme-stats)

Therefore, I propose closing this issue if that is okay with you 🤔?

**Comment by silverwind** [comment]
Fine with me. Showing the actual percentage somewhere would be a nice feature to avoid such questions in the future, maybe in a tiny text centered below the "S", and maybe optionally.

**Comment by rickstaa** [comment]
@silverwind I just created https://github.com/anuraghazra/github-readme-stats/pull/2858, which gives the user the ability to replace the rank level with the rank progress. Feel free to create a pull request if you still want to show the rank level and progress. I couldn't find an excellent way to simultaneously show them both on the card.

**Comment by rickstaa** [comment]
![Anurag's GitHub stats](https://github-readme-stats-git-addprogressrankicon-rickstaa.vercel.app/api?username=silverwind\&rank_icon=progress)

**Comment by silverwind** [comment]
Looks great. I'm happy with only showing the percentage.

**Comment by rickstaa** [comment]
Merged!
