### ISSUE TITLE
Translated Github Stats not working

### ISSUE THREAD

**Issue by AmodeusR** [anuraghazra/github-readme-stats#2839]
### Describe the bug

locale translations are not working, it just breaks the github stats and shows the message "wakatimecard.lastyear Translation locale not found".

only the locale=en or no locale works, the rest breaks the image with the given error. I tried adding a range=[something] but it didn't even have an effect. 

### Expected behavior

The expected behavior would be translating the image instead of breaking it.

### Screenshots / Live demo link

![image](https://github.com/anuraghazra/github-readme-stats/assets/29683600/737321f2-de6f-4b74-afd4-d4b7fb9c53b5)

**Comment by rickstaa** [comment]
@AmodeusR, thanks for the feature report. Not all translations were already added. I think the fallback (i.e. `en`) is not triggered in your case. This should be fixed 👍🏻.

https://github.com/anuraghazra/github-readme-stats/blob/6cbb08e218a57b4e7ecd8b2ad3485cba0f7765f5/src/translations.js#L391-L406

**Comment by rickstaa** [comment]
@AmodeusR, thanks for the feature report. Not all translations were already added. I think the fallback (i.e. `en`) is not triggered in your case. This should be fixed 😅.

https://github.com/anuraghazra/github-readme-stats/blob/6cbb08e218a57b4e7ecd8b2ad3485cba0f7765f5/src/translations.js#L391-L406

Would it be possible for you to create a PR to fix this (see https://github.com/anuraghazra/github-readme-stats/blob/master/CONTRIBUTING.md)? Otherwise, I will take a look later this month 👍🏻.
