### ISSUE TITLE
Incorrect total commits

### ISSUE THREAD

**Issue by ilyamixaltik** [anuraghazra/github-readme-stats#2922]
### Describe the bug

Incorrect total commits. I have 224 commits listed for the entire time. Although in the statistics from GitHub, 1.5k commits were made only this year.

### Screenshots / Live demo link

![Github stats](https://github-readme-stats.vercel.app/api?username=ilyamixaltik&include_all_commits=true&theme=dark&show_icons=true&count_private=true)

**Comment by qwerty541** [comment]
@ilyamixaltik Situation when card showing 0 commits is well known issue when using `include_all_commits=true` query option caused by the upstream rest API returning an error or timing out (see https://github.com/anuraghazra/github-readme-stats/issues/1515). This incorrect response is then cached. Should automatically be solved in 4 hours. You can [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) to mitigate this problem.

If your question is about showing your private contributins, our API no longer support `count_private=true` query option. You should [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) using own GitHub PAT (Personal Access Token) to show private contributions on the card.

**Comment by ilyamixaltik** [comment]
Helped, thanks
