### ISSUE TITLE
Maximum retries exceeded - with additional repos to pin - PAT_1

### ISSUE THREAD

**Issue by readyyyk** [anuraghazra/github-readme-stats#2935]
### Describe the bug

Maximum retries exceeded
Add env variable called PAT_1 with your gh token to vercel

### Expected behavior

show an image 

### Screenshots / Live demo link

![image](https://github.com/anuraghazra/github-readme-stats/assets/78100125/c0b3c08f-801d-4850-abb8-8cb7448b38a4)

### Additional context

jul 12 19:15

**Comment by rcamarano** [comment]
Hi, i've got the same problem here. 
My recomendation is to make a fork form the original repo and then, deploy it on your own vercel app.
This worked very well for me.
Walktrough the tutorial on READ ME file form the original repo:
"
Deploy on your own
On Vercel
📽️ [Check Out Step By Step Video Tutorial By @codeSTACKr](https://youtu.be/n6d4KHSKqGk?t=107)

Since the GitHub API only allows 5k requests per hour, my https://github-readme-stats.vercel.app/api could possibly hit the rate limiter. If you host it on your own Vercel server, then you do not have to worry about anything. Click on the deploy button to get started!

    Note Since https://github.com/anuraghazra/github-readme-stats/pull/58, we should be able to handle more than 5k requests and have fewer issues with downtime 😁.

Note If you are on the [Pro (i.e. paid)](https://vercel.com/pricing) Vercel plan, the [maxDuration](https://vercel.com/docs/concepts/projects/project-configuration#value-definition) value found in the [Vercel.json](https://github.com/anuraghazra/github-readme-stats/blob/master/vercel.json) can be increased when your Vercel instance frequently times out during the card request. You are advised to keep this value lower than 30 seconds to prevent high memory usage.
"

This will make your own links for the stats so it won't broke down when the limit access was reached.

Hope that's helpful.
Cheers!

**Comment by hdaisywd** [comment]
Hi, I simply added  &PAT_1 to the end of my github link and it worked for me.

**Comment by rcamarano** [comment]
Hey good to know, much simplier than deploying another project.!

**Comment by qwerty541** [comment]
Please check https://github.com/anuraghazra/github-readme-stats/issues/1471. This is caused by GitHub's rate limits being reached. The only way to solve this is to [deploy your own vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own). Adding a random string like `&PAT_1` or `&ANY_RANDOM_STRING_THAT_IS_NO_QUERY` or changing to HTTPS works because this breaks the cache.
