### ISSUE TITLE
Total commits is zero if include_all_commits=true

### ISSUE THREAD

**Issue by littlewhitecloud** [anuraghazra/github-readme-stats#3005]
### Describe the bug

```markdown

<img src="https://github-readme-stats.vercel.app/api?username=littlewhitecloud&show_icons=true&count_private=true&custom_title=My%20GitHub%20stats&bg_color=30,7200BF,AD39B7&icon_color=fafafa&text_color=fafafa&title_color=fafafa&border_color=290079&border_radius=14&include_all_commits=true&line_height=30">

```
<img src="https://github-readme-stats.vercel.app/api?username=littlewhitecloud&show_icons=true&count_private=true&custom_title=My%20GitHub%20stats&bg_color=30,7200BF,AD39B7&icon_color=fafafa&text_color=fafafa&title_color=fafafa&border_color=290079&border_radius=14&include_all_commits=true&line_height=30">

### Expected behavior

Total commits isn’t zero

### Screenshots / Live demo link

<img src="https://github-readme-stats.vercel.app/api?username=littlewhitecloud&show_icons=true&count_private=true&custom_title=My%20GitHub%20stats&bg_color=30,7200BF,AD39B7&icon_color=fafafa&text_color=fafafa&title_color=fafafa&border_color=290079&border_radius=14&include_all_commits=true&line_height=30">

### Additional context

/

**Comment by qwerty541** [comment]
@littlewhitecloud Situation when card showing 0 commits is well known issue when using `include_all_commits=true` query option caused by the upstream rest API returning an error or timing out (see https://github.com/anuraghazra/github-readme-stats/issues/1515). This incorrect response is then cached. Should automatically be solved in 4 hours. You can [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) to mitigate this problem.
