### ISSUE TITLE
Page github for badge creation

### ISSUE THREAD

**Issue by Angelk90** [anuraghazra/github-readme-stats#301]
**Is your feature request related to a problem? Please describe.**

To create a badge, you need to read the documentation carefully and some things may change over time and add new features.

**Describe the solution you'd like**

The creation of a page on github that will guide you in the creation, with all the possible steps and also show you a preview of how it should be and then provide you with the code, would be an excellent solution.

**Comment by nombrekeff** [comment]
That would be cool, although it will have the same problems. If something changes, you will need to adjust it manually as well. 

It would be an excellent tool to have for sure, but will not solve the issues you are listing. We try to keep backward compatibility, so it should not break that often. New features are another thing; they must be updated by hand (or automated).

**Comment by anuraghazra** [comment]
@Angelk90 you are talking about a visual editor to build the cards right? yeah i have it planned i even started to work on it but then stopped it because of time limitations. 


Yes @nombrekeff is right we have to make sure that everything is update and it is really hard to keep that in sync. yes i think we can somewhat automate the process but still it wouldn't be easy.

**Comment by Angelk90** [comment]
@anuraghazra : Are there any news?

**Comment by Angelk90** [comment]
@anuraghazra : Are there any news?
