### ISSUE TITLE
Something went wrong! file an issue at https://tiny.one/readme-stats

### ISSUE THREAD

**Issue by harshkanani204** [anuraghazra/github-readme-stats#3114]
### Describe the bug

This is what is being shown in my github profile.

Maximum retries exceeded.
Please add an env variable called PAT_1 with your github token in vercel

### Expected behavior

Should show stats.

### Screenshots / Live demo link

![image](https://github.com/anuraghazra/github-readme-stats/assets/75885610/735dc4b7-9d3b-4e62-b61f-26ec649f5de5)

**Comment by Magnumv44** [comment]
Try changing part of the starting address from **https://github-readme-stats.vercel.app** to **https://github-readme-stats-sigma-five.vercel.app**

**Comment by rickstaa** [comment]
> Try changing part of the starting address from **https://github-readme-stats.vercel.app** to **https://github-readme-stats-sigma-five.vercel.app**

@Magnumv44 That is not a future-proof solution since then that Vercel instance will be overloaded (see https://github.com/anuraghazra/github-readme-stats/issues/1471 for more information. The best way to solve this is to [deploy your own Vercel instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own).
