### ISSUE TITLE
Add query parameter for amount of languages shown in laguages card

### ISSUE THREAD

**Issue by alexaoh** [anuraghazra/github-readme-stats#322]
It would be nice if query parameter could be added to top-langs, e-g. amount = 7, to show wanted amount of top languages in the card (7 in this case). /src/fetchers/top-languages-fetcher.js fetches the first 10 languages and slices the list so that the returned result only contains the top 5 languages. 

The proposed query parameter 'amount'  could change the slicing, so that the user has control over how many of the top languages he/she wants to display (up to 10 in this case).

**Comment by James-Oswald** [comment]
I second this. It would also be nice if when you hide a language, It would pull your next most used language rather then just decrease the number of languages shown by one, always keeping that number at the "amount" param.

**Comment by lrusso96** [comment]
Hi @alexaoh and @James-Oswald.
Since e9019c1453dc81b967417a1511c275052d31ba1f you can use `langs_count` parameter to achieve this.

For your top-10 languages you should have:
![alex](https://github-readme-stats.vercel.app/api/top-langs/?username=alexaoh&langs_count=10&layout=compact)
![james](https://github-readme-stats.vercel.app/api/top-langs/?username=James-Oswald&langs_count=10&layout=compact)

Hope it helps.

**Comment by James-Oswald** [comment]
This is exactly what I was waiting for, Thanks for the update!

**Comment by lrusso96** [comment]
@alexaoh I think you can close the issue now.

**Comment by anuraghazra** [comment]
implemented in #445

**Comment by alexaoh** [comment]
Great work!
