### ISSUE TITLE
Maximum Retries Exceeded

### ISSUE THREAD

**Issue by ShichenQiao** [anuraghazra/github-readme-stats#3226]
### Describe the bug

My status board shows, "Something went wrong, please file an issue here." The specific error messages are "Maximum Retries Exceeded" and "Downtime due to GitHub API rate limit". Link: https://github.com/ShichenQiao

### Expected behavior

Something like this 
<img width="697" alt="image" src="https://github.com/anuraghazra/github-readme-stats/assets/71228724/b71b6272-bed6-42fe-ac47-a310db8d6480">

### Screenshots / Live demo link

<img width="876" alt="image" src="https://github.com/anuraghazra/github-readme-stats/assets/71228724/893a306a-077d-4b88-893e-b057ea48690a">

**Comment by Prasantkumar987** [comment]
I also faced same problem, but after an hour it came back

**Comment by qwerty541** [comment]
@ShichenQiao @Prasantkumar987 
As written in the error description on the card, this caused by GitHub API rate limit due to high load, you are able to wait until public instance will be no longer limited or [deploy your own instance](https://github.com/anuraghazra/github-readme-stats#on-vercel) to avoid these problem.
