### ISSUE TITLE
what‘s wrong? How to solve?

### ISSUE THREAD

**Issue by gao-ji-kai** [anuraghazra/github-readme-stats#3294]
![image](https://github.com/anuraghazra/github-readme-stats/assets/88011511/34da2bda-a9b3-400c-8da2-af05678303f6)

**Comment by gao-ji-kai** [comment]
solve

**Comment by qwerty541** [comment]
Hey, @gao-ji-kai! You can see this when upstream GitHub API respond with error due to some reason during fetching stats card data. It should be resolve automatically after some time. Recently we merged https://github.com/anuraghazra/github-readme-stats/pull/3238 which improved confusing behavior of showing 0 commits, currently we show error card instead.
