### ISSUE TITLE
Request for Permission to Add Burmese Translation to Document

### ISSUE THREAD

**Issue by LinThit27** [anuraghazra/github-readme-stats#3555]
### Is your feature request related to a problem? Please describe.

This feature isn't related to a problem

### Describe the solution you'd like

As a native speaker, I am confident in my ability to manage this effectively.

### Describe alternatives you've considered

None

### Additional context

# Request for Permission to Add Burmese Translation to Document

May I kindly seek your permission to add a Burmese translation to this document? I believe this addition would enhance its accessibility and value for a wider audience. Your approval in this matter would be greatly appreciated. Thank you for considering my request.

**Comment by qwerty541** [comment]
Hey, @LinThit27! Thanks for your interest in our project and intention to contribute. In nearest future we're going either to remove documentation translations from repository or migrate on automatic translations. We're making this decision for these reasons:

- Most of documentation translations are outdated and hardly someone will completely up to date them.
- Our team cannot properly review pull requests with translations since we don't know all these languages.
- Removing translations will decrease overall efforts for project maintenance.

For these reasons currently we don't review documentation translations pull requests.
