### ISSUE TITLE
Top language card not showing Python

### ISSUE THREAD

**Issue by ParanoidAndroid19** [anuraghazra/github-readme-stats#358]
**Describe the bug**
Despite have 10 repos containing only python code and just 1 repo having jupyter notebook, python is not shown and jupyter notebook is at 66%.

**Expected behavior**
Python should be the shown instead of jupyter notebook.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
Live demo:
[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=ParanoidAndroid19&layout=compact&hide=swift)](https://github.com/anuraghazra/github-readme-stats)

**Comment by rossjrw** [comment]
I'm seeing a similar issue - I've made a bunch of Typescript/Vue projects recently, but neither of those languages are on my stats.

**Comment by anuraghazra** [comment]
This is expected behaviour and not a bug.

@ParanoidAndroid19 jupyter notebook code is always larger.

These are some big files: 
387kb & 286kb
- https://github.com/ParanoidAndroid19/SMS-Spam-Detection/blob/master/.ipynb_checkpoints/Spam%20Detection%20Naive%20Bayes-checkpoint.ipynb
- https://github.com/ParanoidAndroid19/SMS-Spam-Detection/blob/master/.ipynb_checkpoints/original-checkpoint.ipynb

It does not matter if you have 100 repos of python code. it's about how much code you have in your repos in terms of bytes. 

see #136 https://github.com/anuraghazra/github-readme-stats/issues/136#issuecomment-665172181
