### ISSUE TITLE
Streak only tracks to January 1st

### ISSUE THREAD

**Issue by daniel-maxwell** [anuraghazra/github-readme-stats#3733]
### Describe the bug

My current streak only tracks from January 1st of this year currently (111 days).

### Expected behavior

The streak count should last the full length of the streak (starting in May last year in my case), so the count should be around 352 days.

### Screenshots / Live demo link

<a href="https://git.io/streak-stats"><img src="https://streak-stats.demolab.com?user=daniel-maxwell&theme=dark&card_width=450&background=45%2C1E1842%2C5847C2" alt="GitHub Streak" /></a>

My Contributions graph:
![image](https://github.com/anuraghazra/github-readme-stats/assets/66431847/9aaf672a-5580-41c5-ba6e-0b5f872c665f)

### Additional context

Oddly, when I set up the stats tracker for the first time yesterday it initially showed the full count. When I checked back today, it showed an incorrect count.

**Comment by Mohsin370** [comment]
Hi @daniel-maxwell , 

This issue is from a different repository. When I click on your live demo link it does opens up that repository. https://github.com/DenverCoder1/github-readme-streak-stats

I had a similar issue with the stats count, that is possibly due to the timezone difference.

**Comment by qwerty541** [comment]
Hey @daniel-maxwell. I'm closing this issue since it's not related to current repository. Your problem should be discussed there: https://github.com/DenverCoder1/github-readme-streak-stats

However here is a comment about your problem from streak stats card creator: https://github.com/DenverCoder1/github-readme-streak-stats/issues/288#issuecomment-1200029137. Hope this will help to resolve your problem.
