### ISSUE TITLE
Deployment paused by owner

### ISSUE THREAD

**Issue by Honzoraptor31415** [anuraghazra/github-readme-stats#3854]
### Describe the bug

Whenever you try to access the website you'll get one of these:

![image](https://github.com/user-attachments/assets/69eefe1e-45ad-40b8-8384-07e094490d12)

And if you have an image linked in your profile readme, it doesn't load.

Why is the deployment paused? And do I understand it correctly that it was paused by @anuraghazra ? If so, why, what is going on?

And just in case you were wondering, yes, I did try to look at other peoples profiles if they're experiencing the same issue and yes, I did try a different browser, even a different device, but that is not a solution here.

**Comment by raselmandol** [comment]
@Honzoraptor31415 waiting for the owner to solve this issue

**Comment by Rudxain** [comment]
dupe of #3851. But this issue is more informative, so I guess it's alright

**Comment by lmliheng** [comment]
Private deployment, like this

![image](https://github.com/user-attachments/assets/c1887875-38c1-43df-b825-5706fac723f7)

**Comment by Akshay-Vs** [comment]
You have the option to fork the repository and deploy it on Vercel independently

**Comment by aryankeluskar** [comment]
Yep, I believe his server is rate-limited. I recommend checking out this video https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s for fixing it!

**Comment by qwerty541** [comment]
Hey guys! All this time the public instance was deployed on Vercel on the account with enterprise plan provided for free for Anurag. I just received a message from Anurag that Vercel stopped their OSS sponsorship and account was returned to basic plan, so when the limits was exceeded the deployment was paused. As I understand, at the moment Anurag returned it to work with own money, but in the near future we have to migrate on another cloud provider because Vercel is very expensive. Therefore, deployment on the [github-readme-stats.vercel.app](https://github-readme-stats.vercel.app/) will be shutdown soon. For now I recommend you all to [deploy your own Vercel instances](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#on-vercel) in order to avoid impact of future shutdown of public instance.

**Comment by Rudxain** [comment]
I want to contribute to the lang-card GH-Action:
https://github.com/anuraghazra/github-readme-stats/blob/d91f6295f6d6caac002d117011f74ff3d2dbd642/readme.md?plain=1#L501

**Comment by xxshubhamxx** [comment]
Facing the same issue!

**Comment by Cactusinhand** [comment]
@xxshubhamxx maybe you can try this tool: [GitHubCard](https://githubcard.com)
