### ISSUE TITLE
Error fetching resource

### ISSUE THREAD

**Issue by jexlor** [anuraghazra/github-readme-stats#3855]
### Describe the bug

Top languages link can't fetch resource to show statistics on your profile.

The reason might be the recent issue with project itself, but in case if it's not i'll open that issue

### Screenshots / Live demo link

![Screenshot from 2024-07-18 12-17-08](https://github.com/user-attachments/assets/f1408706-11e0-41a5-8255-046112cb11bb)

**Comment by Akshay-Vs** [comment]
There's a deployment issue. To work around it, you can fork the repository and host it on your own Vercel instance until the problem is fixed

**Comment by Akshay-Vs** [comment]
There's a deployment issue. To work around it, you can fork the repository and host it yourself on Vercel until the problem is fixed

**Comment by lmliheng** [comment]
You can refer to # 3854 # 3852 
author's README for a tutorial on private deployment of vercel

**Comment by aryankeluskar** [comment]
Yep, I believe his server is rate-limited. I recommend checking out this video https://www.youtube.com/watch?v=n6d4KHSKqGk&t=107s for fixing it!

**Comment by qwerty541** [comment]
Hey guys! All this time the public instance was deployed on Vercel on the account with enterprise plan provided for free for Anurag. I just received a message from Anurag that Vercel stopped their OSS sponsorship and account was returned to basic plan, so when the limits was exceeded the deployment was paused. As I understand, at the moment Anurag returned it to work with own money, but in the near future we have to migrate on another cloud provider because Vercel is very expensive. Therefore, deployment on the [github-readme-stats.vercel.app](https://github-readme-stats.vercel.app/) will be shutdown soon. For now I recommend you all to [deploy your own Vercel instances](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#on-vercel) in order to avoid impact of future shutdown of public instance.
