### ISSUE TITLE
Adding more languages in the language card.

### ISSUE THREAD

**Issue by Alpha-1729** [anuraghazra/github-readme-stats#402]
How to add my 10 top languages in the language card.

**Comment by lrusso96** [comment]
Hi @Alpha-1729, since e9019c1453dc81b967417a1511c275052d31ba1f you can use `langs_count` parameter.

For your top-10 languages you should type:
![Foo](https://github-readme-stats.vercel.app/api/top-langs/?username=Alpha-1729&langs_count=10)

Note: it seems that in your public repositories you have used only 5 different languages; if you add more content, the badge will be populated with the new programming languages.

**Comment by anuraghazra** [comment]
Closing this in favor of #445
