### ISSUE TITLE
Readme contains some mistyped parameters

### ISSUE THREAD

**Issue by pnxdxt** [anuraghazra/github-readme-stats#446]
**Describe the bug**
When describing some parameters, it is recommended to use '?' before the query parameter.

**Expected behavior**
basically `?username` is the only parameter using '?'
The readme should indicate that you have to use '&' before the other query parameters.

**Fix**

Replace `?hide` by `&hide`

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**

![Capture d’écran 2020-09-09 à 22 09 47](https://user-images.githubusercontent.com/5941125/92648178-56748500-f2e9-11ea-8965-b28b37e9df23.jpg)

**Additional context**
PR correcting this mistake in the different languages : [pnodet : github-readme-stats/pull/346](https://github.com/anuraghazra/github-readme-stats/pull/346)

**Comment by anuraghazra** [comment]
Hi @pnodet thanks for reporting the issue,

Actually this is not an huge as you know we add `?` question mark when defining URL parameters and we use question mark once at the start and after that we cannot use `?` we have to use `&` since it's more than two parameters.

> basically ?username is the only parameter using '?'
No it does not mean username is only using ? you can also add any other param at first and it has to use ? instead of &
It's just how URL parameters work.


> The readme should indicate that you have to use '&' before the other query parameters.
I used `?hide` to indicate that hide is an URL parameter.

**Comment by pnodet** [comment]
I do agree that this is not a major issue, but from a personal experience I had some trouble with setting up my readme because of this.

I think that it could be helpful for other when discovering this repo and trying to setup their own readme.

I linked a pull request where I corrected this, helping other to apprehend the installation.
