### ISSUE TITLE
Github Stats are not updating by contributing at main Github profile page !

### ISSUE THREAD

**Issue by Alphasaurs** [anuraghazra/github-readme-stats#483]
**Describe the bug**
Github Stats are not updating by contributing at main Github profile page !

**Expected behavior**
I am contribution to open source and then I encounter this bug that on my github profile the stats are not updating. It should be dynamic. I wants to highlight when I click the stats card it is updated as shown in below gif.

**Link to reproduce bug**
Main github profile
https://github.com/Alphasaurs

After clicking stats link, it is updated
https://github-readme-stats.vercel.app/api?username=alphasaurs&theme=buefy&show_icons=buefy

**Comment by anuraghazra** [comment]
This is expected behaviour we have setup min of 2 hour cache.

**Comment by Alphasaurs** [comment]
Hello @anuraghazra it is not due to cache as link is updating dynamically https://github-readme-stats.vercel.app/api?username=alphasaurs&theme=buefy&show_icons=buefy

**Comment by anuraghazra** [comment]
it is because github respects the cache headers and caches the image in their camo CDN

https://camo.githubusercontent.com/d9d30fd2def76e83377d773945badfa17c4ae034/68747470733a2f2f6769746875622d726561646d652d73746174732e76657263656c2e6170702f6170693f757365726e616d653d616c7068617361757273267468656d653d62756566792673686f775f69636f6e733d6275656679
