### ISSUE TITLE
Bad font on GitHub mobile.

### ISSUE THREAD

**Issue by harshhhdev** [anuraghazra/github-readme-stats#571]
**Describe the bug**
The font on for the stats on GitHub mobile looks ugly, and is not what is used in the website.

**Expected behavior**
Same font as github.com on mobile phones.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
![image](https://user-images.githubusercontent.com/69592270/95913394-213cd600-0d72-11eb-8bb5-4225bf0229e3.png)

**Comment by anuraghazra** [comment]
related to https://github.com/anuraghazra/github-readme-stats/issues/215

**Comment by Andre601** [comment]
I face a similar issue with the code quality card on the github app (running android)

It only displays the circle with the rank and is otherwise blank.

Image:
![SmartSelect_20201209-143347_GitHub.jpg](https://user-images.githubusercontent.com/11576465/101636976-63119200-3a2c-11eb-9276-9c12afdbf00b.jpg)

**Comment by rickstaa** [comment]
This appears to be fixed. See https://github.com/anuraghazra/github-readme-stats/issues/899#issuecomment-877199309. I will close the related issues for now. If anyone is still experiencing issues feel free to leave a comment.
