### ISSUE TITLE
Names ending on "S"

### ISSUE THREAD

**Issue by Th3Ph4nt0m** [anuraghazra/github-readme-stats#610]
**Is your feature request related to a problem? Please describe.**
My Name ends on "S". The title of my card is "Henrik S's stats".

**Describe the solution you'd like**
The title should be "Henrik S' stats"

**Describe alternatives you've considered**
Tried to change the "S" to my full surname, same problem.

**Comment by harshhhdev** [comment]
@anuraghazra can I work on this?

**Comment by nthnchu** [comment]
@Th3Ph4nt0m This is definitely an issue, but in the meantime you can use the custom title query parameter. Try using `&custom_title=Henrik%20S%27%20stats` as a query parameter as a workaround.

**Comment by anuraghazra** [comment]
Ahhh this happened because your name ends with capital S. 

it's a quick fix. 

https://github.com/anuraghazra/github-readme-stats/blob/master/src/cards/stats-card.js#L80

![image](https://user-images.githubusercontent.com/35374649/98150276-64fba900-1ef4-11eb-8e0f-9ac5e2074e17.png)


@harshhhdev yeah you can work on it

**Comment by nthnchu** [comment]
@anuraghazra @harshhhdev I already made the PR. @Th3Ph4nt0m It should work without the workaround once merged.

**Comment by anuraghazra** [comment]
@nthnchu thanks for the fix!

**Comment by anuraghazra** [comment]
closed by #612
