### ISSUE TITLE
[Feature request] System based theme

### ISSUE THREAD

**Issue by NuroDev** [anuraghazra/github-readme-stats#66]
Not a overly urgent feature, but would be a neat feature to add support for system theme detection using CSS' `prefers-color-scheme` media attribute to fetch the system theme color and set the stats/repo card styles based on it.
Example:
```
![Anurag's github stats](https://github-readme-stats.vercel.app/api?username=anuraghazra&system_theme=true)
```

**Comment by anuraghazra** [comment]
Hi @NuroDev thanks for requesting the feature.

Well, i'm not sure if this is possible because the rendered svg would be uploaded/served from the github cdns so i don't think css-prefer-color-scheme would work. while fixing #45 i also faced this issue because user-agent wasn't the browser's it was github's cdn `camo-github`
