### ISSUE TITLE
Other owner repos in lang card

### ISSUE THREAD

**Issue by hypewsthedev** [anuraghazra/github-readme-stats#672]
**Is your feature request related to a problem? Please describe.**
Add a way to show languages from other repos that you dont own but contribute to

**Describe the solution you'd like**
Lets say I contribute to a JavaScript repo, it would be cool if that would be added to the languages card

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Electrenator** [comment]
This would be great to see, especially if it also ignores languages written by other users. To achieve this the language detection would need to be based on the commits a person made instead of the repositories a person owns. This would also definitely become expensive API resource limit wise.

I currently can't find a way to get this information from the GitHub GraphQL API but might continue searching for a way at a later date. If we do get this working this change would probably also adress isue #450

**Comment by Electrenator** [comment]
It doesn't look like this data is currently not retrievable via the GitHub API. This would need to be calculated on the github-readme-stats server, which would add ***a lot*** of overhead when implemented (with cloning and detecting languages). Don't think that this is currently possible without easy acces to that data via an API.

**Comment by AKlaus** [comment]
I fully support the motion.
Perhaps, making the `ownerAffiliations` parameter optional in the below query would solve the problem:

```
query userInfo($login: String!) {
  user(login: $login) {
    # fetch only owner repos & not forks
    repositories(ownerAffiliations: OWNER, isFork: false, first: 100) {
      nodes {
        name
        languages(first: 10, orderBy: {field: SIZE, direction: DESC}) {
          edges {
            size
            node {
              color
              name
            }
          }
        }
      }
    }
  }
}
```

So it would be 
```
...
repositories(isFork: false, first: 100) {...}
...
```
