### ISSUE TITLE
Consider combining results from from GitHub and GitLab ?

### ISSUE THREAD

**Issue by amindadgar** [anuraghazra/github-readme-stats#753]
**Is your feature request related to a problem? Please describe.**
I was using the readme status for my account and I consider how it can combine results from GitHub and GitLab. At this time it seems this readme-stats is working just from GitHub results.

**Describe the solution you'd like**
if _github-readme-stats_ can get data from both GitHub and GitLab it can be much more concise for user profile.

**Comment by xaviergmail** [comment]
I would also love this feature

**Comment by marchbold** [comment]
same!

**Comment by PandaFoss** [comment]
I think this is an incredible idea. Since in the readme you try to show how much time you spend on development, I think it would be nice to show the whole thing and not just one platform.
Maybe the `gitlab` (boolean) option could be added, and if no `gitlab_username` is given it is assumed to be the same as the GitHub one (by default the stats should be taken only from GitHub, of course).

**Comment by yuredev** [comment]
This feature would be great!
