### ISSUE TITLE
Top languages to use commits not personal repos

### ISSUE THREAD

**Issue by rijobro** [anuraghazra/github-readme-stats#833]
**Is your feature request related to a problem? Please describe.**
If I understand correctly, the top languages card only uses non-forked repos to determine top languages.

This is problematic if the majority of contributions are made to forked repositories. As an example, pytorch's main contributor probably writes in python >90%, yet if they have a handful of personal repos containing bash scripts, that would show up as their main language.

One of the best features of github is the ability to collaborate on projects, a metric that doesn't include this information seems somewhat lacking.

**Describe the solution you'd like**
I'd like the metric to be based on the languages in commits, whether to your own repos or not.

**Comment by anuraghazra** [comment]
Hi @rijobro yes i can understand what you are saying.

@Bas950 is implementing this in #505

Although only thing i'm concerned about is with the forks included the stats can get very manipulative because users can fork large repos to increase their stats.

Maybe instead of exclude_repo we can do include_repo that way users would manually include the repo.

**Comment by rijobro** [comment]
> Although only thing i'm concerned about is with the forks included the stats can get very manipulative because users can fork large repos to increase their stats.

I wouldn't implement it so that it would check the languages of the forked repos, just the user's **commits** in these repos. That way, forking a repo won't change anything, only contributing to it will.

**Comment by anuraghazra** [comment]
> > Although only thing i'm concerned about is with the forks included the stats can get very manipulative because users can fork large repos to increase their stats.
> 
> I wouldn't implement it so that it would check the languages of the forked repos, just the user's **commits** in these repos. That way, forking a repo won't change anything, only contributing to it will.

There are some limitations regarding github api.. 
GitHub does not provides any way to check if a commit has X amount of languages and if we try to implement it ourselves it would not be viable to do so because we have to process all the commits and calculate how much code there is in those commits which is a slow process.

**Comment by rijobro** [comment]
Hm that's too bad...
