### ISSUE TITLE
API Doesnt Show Forked Repos in Top-Languages

### ISSUE THREAD

**Issue by Itz-Hyperz** [anuraghazra/github-readme-stats#869]
**Describe the bug**
So, when install [the top languages](https://hyper.dev/github) It actually just shows the repositories I have created, not the ones I have forked and worked on. Can you fix this?

**Expected behavior**
I expect it to include all of my repos, not just ones I create.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
[here](https://hyperz.dev/github)

**Additional context**
If there is a fix for this, please let me know!

Or, if this is a common thing, and people don't want it, maybe show how I could add it?

**Comment by jctaoo** [comment]
I think it's better to count language-use in all my commits on GitHub instead of only my repositories. Because top language card shows which programming language I write on GitHub, and in some times we work for org or forked project. It means top language data only counting by my repositories can not show real me.
