### ISSUE TITLE
Star count not showing correctly

### ISSUE THREAD

**Issue by dattatray-patil** [anuraghazra/github-readme-stats#891]
**Describe the bug**
I am not able to see the number of stars correctly.

**Expected behavior**
It should show the correct number of stars.

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
Please find below star screen shot.
![image](https://user-images.githubusercontent.com/60019982/108395068-4ef8c680-720d-11eb-891c-2ec9a415ade2.png)

**Comment by anuraghazra** [comment]
This is correct, you only gained 1 star with is from https://github.com/dattatray-patil/Profile

**Comment by dattatray-patil** [comment]
Thanks Anurag. I removed star now. 
You can close the issue.

**Comment by SunnyKumar-Jonwal** [comment]
I Can't See Stars And Not See The Bar Of Which Languages Repository I Uploaded In My Profile.
What Should I Do Please Help Me
![S1](https://github.com/anuraghazra/github-readme-stats/assets/106869482/d0cd1136-3f2b-4ebf-ba78-e6dbf9310657)

**Comment by qwerty541** [comment]
@SunnyKumar-Jonwal This is because our public instance is being rate-limited by underlying GitHub API (see https://github.com/anuraghazra/github-readme-stats/issues/1471). You can [deploy your own instance](https://github.com/anuraghazra/github-readme-stats#deploy-on-your-own) using your own GitHub API token in order to fix it or wait until the public instance is longer rate-limited.
