### ISSUE TITLE
User commits not updating

### ISSUE THREAD

**Issue by danBamikiya** [anuraghazra/github-readme-stats#927]
**Describe the bug**
My number of my commits being displayed are mostly static(not increasing) and sometimes reducing.

**Expected behavior**
My commits number is supposed to increase

**Screenshots / Live demo link (paste the github-readme-stats link as markdown image)**
User: danBamikiya

**Additional context**

**Comment by Nirav-Madhani** [comment]
Please refer: 
https://github.com/anuraghazra/github-readme-stats/issues/935#issuecomment-803246873
The problem is with response headers.

Example: `http://206.167.183.187/chart.png`
Response Headers : 
```
HTTP/1.1 200 OK
Date: Sat, 20 Mar 2021 05:33:38 GMT
Server: Apache/2.4.29 (Ubuntu)
Accept-Ranges: bytes
Content-Length: 23443
Pragma: no-cache
Cache-Control: max-age=0, no-cache, no-store, must-revalidate
Expires: Thu, 1 Jan 1970 00:00:00 GMT
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
Content-Type: image/png
```
And For:
`https://github-readme-stats.vercel.app/api?username=Nirav-Madhani&show_icons=true&theme=algolia&include_all_commits=true&count_private=true`

Response Headers:
```
HTTP/2 304 Not Modified
date: Sat, 20 Mar 2021 05:36:24 GMT
content-length: 0
x-vercel-cache: HIT
server: Vercel
x-vercel-id: bom1::sfo1::xwnjj-1616218584243-93ac26e3ad24
strict-transport-security: max-age=63072000; includeSubDomains; preload
cache-control: s-maxage=0
X-Firefox-Spdy: h2
```

I think that this  `cache-control: s-maxage=0` line is creating the problem. Not sure tho.

**Comment by danBamikiya** [comment]
Ok I also thought github could be the problem.
