### ISSUE TITLE
[Feature Request] Allow `show_icons` to be used with repos' cards

### ISSUE THREAD

**Issue by Paveloom** [anuraghazra/github-readme-stats#95]
**Is your feature request related to a problem? Please describe.**
Since most of my repositories don't have any stars and aren't forked by anyone (he-he...), I would like to be able to hide these stats from the repos' cards. This is how standard GitHub's pins behave.

**Describe the solution you'd like**
There's already a `show_icons` parameter for stats' cards, to have something similar to this for repositories' cards (excluding this additional information) would be quite pleasant.

**Describe alternatives you've considered**
This feature can also be added as a new parameter, like `show_stats` or something like that.

**Additional context**

![](https://github-readme-stats.vercel.app/api/pin/?username=paveloom-j&repo=Scats.jl)

**Comment by anuraghazra** [comment]
Oh yeah right, github hides the star/fork if they are zero. i'll probably do that too.

But i don't think i will be introducing any other show_repo_stats parameter for manually showing/hiding the star/fork count because i don't want to bloat the APIs with lots of options, i wanted the Github Extra Pins feature to be a bit more strict in terms on customization.

**Comment by Paveloom** [comment]
Yep, this seems to be right now. Thank you.
